# HIPE MASK Experiments

In [1]:
!nvidia-smi -L 2>/dev/null || echo "No NVIDIA GPU visible — switch runtime type."
import sys
print("Python:", sys.version)


GPU 0: Tesla T4 (UUID: GPU-191a84e4-1e26-cfe0-1f9b-59c29017ac4a)
Python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import os, pathlib

In [4]:
DRIVE_BASE = pathlib.Path('/content/drive/MyDrive/Colab Notebooks/HIPE')

In [5]:
DRIVE_BASE.mkdir(parents=True, exist_ok=True)
(DRIVE_BASE / 'runs').mkdir(exist_ok=True)
(DRIVE_BASE / 'logs').mkdir(exist_ok=True)
print('Drive workdir:', DRIVE_BASE)
print('  runs/  ->', list((DRIVE_BASE / 'runs').iterdir())[:5] or '(empty)')
print('  logs/  ->', list((DRIVE_BASE / 'logs').iterdir())[:5] or '(empty)')

Drive workdir: /content/drive/MyDrive/Colab Notebooks/HIPE
  runs/  -> [PosixPath('/content/drive/MyDrive/Colab Notebooks/HIPE/runs/phase0_mask_diag'), PosixPath('/content/drive/MyDrive/Colab Notebooks/HIPE/runs/sd'), PosixPath('/content/drive/MyDrive/Colab Notebooks/HIPE/runs/retriever_at_bgem3'), PosixPath('/content/drive/MyDrive/Colab Notebooks/HIPE/runs/retriever_at_e5small'), PosixPath('/content/drive/MyDrive/Colab Notebooks/HIPE/runs/mask_dbmdz_bert_base_historic_multilingual_cased_M1_L-1_-4_-7.npz')]
  logs/  -> [PosixPath('/content/drive/MyDrive/Colab Notebooks/HIPE/logs/ablations'), PosixPath('/content/drive/MyDrive/Colab Notebooks/HIPE/logs/kfold'), PosixPath('/content/drive/MyDrive/Colab Notebooks/HIPE/logs/k_sweep'), PosixPath('/content/drive/MyDrive/Colab Notebooks/HIPE/logs/agentic'), PosixPath('/content/drive/MyDrive/Colab Notebooks/HIPE/logs/final')]


In [6]:
import os, subprocess
from google.colab import userdata

In [7]:
REPO = 'diana-nurbakova/hipe-insalyon'   # ← edit this: 'org-or-user/repo-name'
WORKDIR = '/content/HIPE'

In [8]:
try:
    GH_TOKEN = userdata.get('GITHUB_TOKEN')
except Exception as e:
    raise SystemExit(
        f"Couldn't read GITHUB_TOKEN from Colab secrets ({e}). "
        "Add it via the Secrets pane (key icon in the sidebar) and toggle "
        "'Notebook access', or use Path B (zip upload) below."
    )

In [9]:
# Fine-grained PATs accept any username; 'oauth2' is the convention.
clone_url = f'https://oauth2:{GH_TOKEN}@github.com/{REPO}.git'

if os.path.exists(WORKDIR):
    subprocess.check_call(['rm', '-rf', WORKDIR])
subprocess.check_call(['git', 'clone', '--depth', '1', clone_url, WORKDIR])

0

In [10]:
# Scrub the token out of .git/config so it isn't accidentally read by
# subsequent !git commands (or echoed if the dir is later inspected).
subprocess.check_call(
    ['git', '-C', WORKDIR, 'remote', 'set-url', 'origin',
     f'https://github.com/{REPO}.git']
)

os.chdir(WORKDIR)
print('HEAD:', subprocess.check_output(
    ['git', 'rev-parse', '--short', 'HEAD']).decode().strip())


HEAD: c21ad00


In [11]:
# INSTALL DEPENDENCIES
!pip install -q --upgrade pip
!pip install -q -e ".[ml,viz,dev]"
# UMAP-learn pulls numba; this can take a minute on a fresh runtime.

  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
  Building editable for hipe (pyproject.toml) ... done


In [12]:
# verify the install
import torch, transformers, sklearn, scipy, umap
print('torch       :', torch.__version__, '  CUDA:', torch.cuda.is_available())
print('transformers:', transformers.__version__)
print('scikit-learn:', sklearn.__version__)
print('scipy       :', scipy.__version__)
print('umap        :', umap.__version__)

torch       : 2.10.0+cu128   CUDA: True
transformers: 5.0.0
scikit-learn: 1.6.1
scipy       : 1.16.3
umap        : 0.5.12


In [13]:
# LOAD SECRETS
import os
from google.colab import userdata

# All secrets below are OPTIONAL for the MASK notebook. The loop tolerates
# missing keys; it only loads what you've added in the Secrets pane.
SECRET_KEYS = [
    'HF_TOKEN',           # optional — only needed for gated HF models
    # Uncomment if you'll run LLM cells in a sister notebook later:
    # 'OPENAI_API_KEY',
    # 'DEEPINFRA_API_KEY',
    # 'ANTHROPIC_API_KEY',
    # 'OPENROUTER_API_KEY',
    # 'OLLAMA_API_KEY',
    # 'OLLAMA_BASE_URL',
]

loaded, missing = [], []
for name in SECRET_KEYS:
    try:
        val = userdata.get(name)
    except userdata.SecretNotFoundError:
        missing.append(name); continue
    except userdata.NotebookAccessError:
        missing.append(f'{name} (no notebook access)'); continue
    if val:
        os.environ[name] = val
        loaded.append(name)
    else:
        missing.append(name)

print('Loaded :', loaded or '(none — that is fine for MASK-only runs)')
print('Missing:', missing or '(none)')

# HuggingFace-specific aliases (the various HF libraries each look at a slightly
# different variable; setting all three keeps `from_pretrained` happy for gated
# models and avoids the interactive `huggingface-cli login` prompt).
if 'HF_TOKEN' in os.environ:
    os.environ.setdefault('HUGGINGFACE_HUB_TOKEN', os.environ['HF_TOKEN'])
    os.environ.setdefault('HUGGING_FACE_HUB_TOKEN', os.environ['HF_TOKEN'])


Loaded : ['HF_TOKEN']
Missing: (none)


In [14]:
# verification
from huggingface_hub import whoami
try:
    print(whoami())
except Exception as e:
    print('No HF token recognised:', e)

{'type': 'user', 'id': '6346f43d9db2aaaf4710d8a6', 'name': 'diananurbakova', 'fullname': 'Diana Nurbakova', 'canPay': False, 'billingMode': 'prepaid', 'periodEnd': 1780272000, 'isPro': True, 'avatarUrl': '/avatars/3efaf7e5a7917cbca4eb0de1bac30e02.svg', 'orgs': [], 'auth': {'type': 'access_token', 'accessToken': {'displayName': 'personal-token', 'role': 'fineGrained', 'createdAt': '2026-03-05T17:50:56.467Z', 'fineGrained': {'canReadGatedRepos': True, 'global': ['discussion.write', 'post.write'], 'scoped': [{'entity': {'_id': '6346f43d9db2aaaf4710d8a6', 'type': 'user', 'name': 'diananurbakova'}, 'permissions': ['repo.content.read', 'repo.access.read', 'repo.write', 'inference.serverless.write', 'inference.endpoints.infer.write', 'inference.endpoints.write', 'user.webhooks.read', 'user.webhooks.write', 'collection.read', 'collection.write', 'discussion.write', 'user.billing.read', 'job.write']}]}}}}


In [15]:
import os, shutil, pathlib

PROJECT = pathlib.Path('/content/HIPE')

In [16]:
if not pathlib.Path('/content/drive/MyDrive').exists():
    raise SystemExit(
        'Drive is not mounted. Re-run Cell 2 first — every cache and log file '
        'is otherwise lost when the runtime disconnects (which it will).'
    )
DRIVE_BASE.mkdir(parents=True, exist_ok=True)

In [17]:
# Symlink the WHOLE runs/ and logs/ trees, not just specific subfolders.
# That way new subdirs (logs/agentic/, logs/k_sweep/, runs/phase0_mask_diag/, ...)
# inherit the persistence automatically without needing to be listed here.
for sub in ('runs', 'logs'):
    src = PROJECT / sub
    dst = DRIVE_BASE / sub
    dst.mkdir(parents=True, exist_ok=True)

    if src.is_symlink():
        # Stale symlink from a prior session — refresh it.
        src.unlink()
    elif src.is_dir():
        for child in list(src.iterdir()):
            target = dst / child.name
            if target.exists():
                # Drive already has this entry — delete the local clone copy.
                if child.is_symlink() or not child.is_dir():
                    child.unlink()
                else:
                    shutil.rmtree(child)
            else:
                shutil.move(str(child), str(target))
        src.rmdir()
    src.symlink_to(dst, target_is_directory=True)
    print(f'  {src}  ->  {dst}')

# Sanity check: writes through the symlink should hit Drive.
probe = PROJECT / 'runs' / '.persistence_probe'
probe.write_text('ok')
assert (DRIVE_BASE / 'runs' / '.persistence_probe').read_text() == 'ok'
probe.unlink()
print('\nPersistence verified — outputs survive runtime disconnects.')

  /content/HIPE/runs  ->  /content/drive/MyDrive/Colab Notebooks/HIPE/runs
  /content/HIPE/logs  ->  /content/drive/MyDrive/Colab Notebooks/HIPE/logs

Persistence verified — outputs survive runtime disconnects.


In [18]:
# test
!pytest -x -q

........................................................................ [ 51%]
.....................................................................    [100%]
141 passed in 14.23s


## QA features and Dateline

In [45]:
# check
from pathlib import Path
import pandas as pd

from hipe.data import load_jsonl
from hipe.subgroup_discovery import detect_dateline

PROJECT = Path(r'/content/HIPE')   # '/content/HIPE' on Colab
insts = load_jsonl(PROJECT / 'data' / 'dataset_reference.jsonl')

# (doc_id, location-mention substring required, gold_at, modal_pred, expected_signal)
HARD_CASES = [
    ('NZZ-1848-10-21-a-p0003',     'Frankfurt',   'PROBABLE', 'TRUE', 'mid_dateline'),
    ('NZZ-1888-03-08-b-p0002',     'Deutschland', 'PROBABLE', 'TRUE', 'dateline_only'),
    ('9838247_1868-02-19_0_0_001', 'ſ',           'PROBABLE', 'TRUE', '(body mention — should NOT fire)'),
    ('EXP-1868-04-22-a-i0042',     'Magdala',     'PROBABLE', 'TRUE', '(body mention — should NOT fire)'),
]

rows = []
for doc, needle, gold, modal, expect in HARD_CASES:
    inst = next(
        (i for i in insts
         if i.document_id == doc
         and any(needle in lm for lm in (i.loc_mentions_list or []))),
        None,
    )
    if inst is None:
        rows.append({'doc_id': doc, 'note': f'no instance with loc containing {needle!r}'})
        continue
    feats = detect_dateline(inst)
    rows.append({
        'doc_id'   : doc,
        'loc'      : (inst.loc_mentions_list or [''])[0],
        'gold'     : gold,
        'modal'    : modal,
        'expect'   : expect,
        **{k.replace('location_', ''): int(v) for k, v in feats.items()},
    })

with pd.option_context('display.max_columns', None, 'display.width', 200):
    print(pd.DataFrame(rows).to_string(index=False))

                    doc_id         loc     gold modal                           expect  is_dateline  is_opening_dateline  is_closing_dateline  is_mid_dateline  dateline_only
    NZZ-1848-10-21-a-p0003   Frankfurt PROBABLE  TRUE                     mid_dateline            1                    0                    0                1              0
    NZZ-1888-03-08-b-p0002 Deutschland PROBABLE  TRUE                    dateline_only            1                    0                    0                1              1
9838247_1868-02-19_0_0_001 Deutſchland PROBABLE  TRUE (body mention — should NOT fire)            0                    0                    0                0              0
    EXP-1868-04-22-a-i0042     Magdala PROBABLE  TRUE (body mention — should NOT fire)            0                    0                    0                0              0


### Population-level dateline diagnostics
Counts how many of the 1,251 instances trigger each dateline sub-feature, and
breaks them down by gold `at` label. The spec's hypothesis is that
`location_dateline_only = 1.0` should heavily skew toward gold FALSE.

In [46]:
import numpy as np
import pandas as pd
from pathlib import Path

from hipe.data import load_jsonl
from hipe.subgroup_discovery import (
    DATELINE_FEATURE_NAMES, dateline_matrix,
)

PROJECT = Path('/content/HIPE')
insts = load_jsonl(PROJECT / 'data' / 'dataset_reference.jsonl')
M = dateline_matrix(insts)
y = np.array([i.at or '?' for i in insts])

df = pd.DataFrame(M, columns=DATELINE_FEATURE_NAMES)
df['at'] = y
print('Fire rates over the full 1,251-instance dataset:')
print(df[list(DATELINE_FEATURE_NAMES)].mean().round(4))

print('\nLabel distribution among instances where location_dateline_only fires:')
print(df.loc[df['location_dateline_only'] == 1.0, 'at'].value_counts(normalize=True).round(3))

print('\nLabel distribution among instances where ANY dateline fires:')
print(df.loc[df['location_is_dateline'] == 1.0, 'at'].value_counts(normalize=True).round(3))


Fire rates over the full 1,251-instance dataset:
location_is_dateline            0.0344
location_is_opening_dateline    0.0088
location_is_closing_dateline    0.0008
location_is_mid_dateline        0.0256
location_dateline_only          0.0096
dtype: float32

Label distribution among instances where location_dateline_only fires:
at
PROBABLE    0.417
TRUE        0.417
FALSE       0.167
Name: proportion, dtype: float64

Label distribution among instances where ANY dateline fires:
at
TRUE        0.488
FALSE       0.302
PROBABLE    0.209
Name: proportion, dtype: float64


### Build the new `SD-H` matrix and confirm dimensions

`SD-H` now includes the 5-d dateline block; total dim should be **47**
(temporal 15 + evidence 13 + verb 7 + hierarchy 3 + dateline 5 + lang 4).

In [47]:
from pathlib import Path
from hipe.data import load_jsonl
from hipe.subgroup_discovery import build_sd_feature_matrix

PROJECT = Path('/content/HIPE')
insts = load_jsonl(PROJECT / 'data' / 'dataset_reference.jsonl')

X, names, meta = build_sd_feature_matrix(insts, config='SD-H', verbose=True)
print(f'\nSD-H matrix : {X.shape}')
print(f'Dateline cols present: '
      f'{[n for n in names if n.startswith("location_")]}')
assert X.shape[1] == 47, f'expected 47-d SD-H, got {X.shape[1]}'
print('OK')

  handcrafted block    : 47-d
Config SD-H: 47 total features (rows: 1251)

SD-H matrix : (1251, 47)
Dateline cols present: ['location_mention_count', 'location_is_dateline', 'location_is_opening_dateline', 'location_is_closing_dateline', 'location_is_mid_dateline', 'location_dateline_only']
OK


In [49]:
import numpy as np, pandas as pd
from hipe.subgroup_discovery import DATELINE_FEATURE_NAMES, dateline_matrix

M = dateline_matrix(insts)
y = np.array([i.at or '?' for i in insts])

# Base rate over the whole dataset.
prior = pd.Series(y).value_counts(normalize=True).round(3)
print('Base rate (all 1,251 instances):')
print(prior.to_string(), '\n')

# Per-feature label breakdown + Δ vs base rate (positive = enriched for that label).
df = pd.DataFrame(M, columns=DATELINE_FEATURE_NAMES).assign(at=y)
records = []
for name in DATELINE_FEATURE_NAMES:
    sub = df.loc[df[name] == 1.0, 'at']
    if len(sub) == 0:
        continue
    dist = sub.value_counts(normalize=True)
    rec = {'feature': name, 'n': len(sub)}
    for lbl in ('TRUE', 'PROBABLE', 'FALSE'):
        p = float(dist.get(lbl, 0.0))
        b = float(prior.get(lbl, 0.0))
        rec[f'{lbl}_pct']   = round(p, 3)
        rec[f'{lbl}_Δprior'] = round(p - b, 3)
    records.append(rec)

pd.set_option('display.width', 200)
print(pd.DataFrame(records).to_string(index=False))

Base rate (all 1,251 instances):
FALSE       0.552
TRUE        0.353
PROBABLE    0.096 

                     feature  n  TRUE_pct  TRUE_Δprior  PROBABLE_pct  PROBABLE_Δprior  FALSE_pct  FALSE_Δprior
        location_is_dateline 43     0.488        0.135         0.209            0.113      0.302        -0.250
location_is_opening_dateline 11     0.818        0.465         0.000           -0.096      0.182        -0.370
location_is_closing_dateline  1     0.000       -0.353         1.000            0.904      0.000        -0.552
    location_is_mid_dateline 32     0.375        0.022         0.281            0.185      0.344        -0.208
      location_dateline_only 12     0.417        0.064         0.417            0.321      0.167        -0.385


In [50]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import recall_score
import numpy as np

dl_cols = [k for k, n in enumerate(names) if n.startswith('location_')]
lang_cols = [k for k, n in enumerate(names) if n.startswith('lang_')]

clf = RandomForestClassifier(n_estimators=300, class_weight='balanced',
                             min_samples_leaf=3, random_state=42, n_jobs=-1)
clf.fit(X[train_idx][:, dl_cols + lang_cols], y[train_idx])
pred = clf.predict(X[test_idx][:, dl_cols + lang_cols])
mr = recall_score(y[test_idx], pred, average='macro',
                  labels=['TRUE','PROBABLE','FALSE'])
print(f'dateline+lang ONLY  MR(at) = {mr:.4f}   (vs majority-class baseline ≈ 0.333)')

dateline+lang ONLY  MR(at) = 0.3636   (vs majority-class baseline ≈ 0.333)


The +0.030 lift over majority confirms the signal is real but tiny — and fully redundant with the rest of the handcrafted block

### Re-evaluate dateline impact on the 188-instance test split

Adds the 5 dateline features to the existing handcrafted RF and reports the
delta on the four `(at)` macro-Recall headline. **Compares against the
on-disk RF baseline already produced by `scripts/rf_with_sd_features.py`** —
no retraining of MASK / contrastive models is required.

In [23]:
import numpy as np, pandas as pd
from pathlib import Path
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import recall_score

from hipe.data import load_jsonl
from hipe.subgroup_discovery import build_sd_feature_matrix

PROJECT = Path('/content/HIPE')
insts = load_jsonl(PROJECT / 'data' / 'dataset_reference.jsonl')
ids_df = pd.read_csv(PROJECT / 'data' / 'v1_baseline_train_test_ids.csv')

# Use the `at` task split (the dateline spec targets `at` macro-Recall).
at_df = ids_df[ids_df['task'] == 'at']
train_ids = set(at_df.loc[at_df['split'] == 'train', 'sample_id'])
test_ids  = set(at_df.loc[at_df['split'] == 'test',  'sample_id'])

train_idx = [k for k, i in enumerate(insts) if i.sample_id in train_ids]
test_idx  = [k for k, i in enumerate(insts) if i.sample_id in test_ids]
print(f'train: {len(train_idx)}   test: {len(test_idx)}')

X, names, _ = build_sd_feature_matrix(insts, config='SD-H', verbose=False)
y = np.array([i.at for i in insts])

dateline_cols = [k for k, n in enumerate(names) if n.startswith('location_')]
non_dateline  = [k for k in range(len(names)) if k not in dateline_cols]

def eval_recall(cols):
    clf = RandomForestClassifier(
        n_estimators=300, class_weight='balanced',
        min_samples_leaf=3, random_state=42, n_jobs=-1,
    )
    clf.fit(X[train_idx][:, cols], y[train_idx])
    pred = clf.predict(X[test_idx][:, cols])
    return recall_score(y[test_idx], pred, average='macro',
                        labels=['TRUE', 'PROBABLE', 'FALSE'])

mr_no_dl = eval_recall(non_dateline)
mr_full  = eval_recall(list(range(len(names))))
print(f'\n  RF macro-Recall(at) without dateline : {mr_no_dl:.4f}')
print(f'  RF macro-Recall(at) with    dateline : {mr_full:.4f}')
print(f'  Δ (dateline contribution)            : {mr_full - mr_no_dl:+.4f}')

train: 1063   test: 188

  RF macro-Recall(at) without dateline : 0.6145
  RF macro-Recall(at) with    dateline : 0.6140
  Δ (dateline contribution)            : -0.0005


### Run QA evidence extraction on the full dataset (GPU)

Loads `deepset/xlm-roberta-base-squad2` (≈ 280 MB), iterates over all 1,251
instances, and caches the resulting 15-d block to Drive so subsequent
ablations don't re-pay the inference cost. Spec budget: ~25 s on T4 — in
practice the model load dominates and the cell takes 1–2 min the first time.

In [58]:
#QA_NPZ.unlink(missing_ok=True)

In [20]:
import numpy as np, json, time
from pathlib import Path

from hipe.data import load_jsonl
from hipe.subgroup_discovery import (
    QAEvidenceExtractor, QA_FEATURE_NAMES, QA_DATELINE_CROSS_FEATURE,
)

PROJECT = Path('/content/HIPE')
RUNS    = PROJECT / 'runs'
QA_NPZ  = RUNS / 'qa_evidence_xlm_r_base_squad2.npz'

insts = load_jsonl(PROJECT / 'data' / 'dataset_reference.jsonl')

if QA_NPZ.exists():
    print(f'Loading cached QA features from {QA_NPZ}')
    cache = np.load(QA_NPZ, allow_pickle=True)
    X_qa  = cache['X']
    spans = cache['spans'].tolist()  # list[dict] of raw answers
else:
    extractor = QAEvidenceExtractor()  # default xlm-roberta-base-squad2
    t0 = time.time()
    X_qa, raw = extractor.extract_matrix(insts, progress=True)
    print(f'Extracted in {time.time() - t0:.1f}s; shape = {X_qa.shape}')
    spans = [{k: v for k, v in r.items() if k.endswith('_span')} for r in raw]
    np.savez(QA_NPZ, X=X_qa, spans=np.array(spans, dtype=object))
    print(f'Cached -> {QA_NPZ}')

cols = list(QA_FEATURE_NAMES) + [QA_DATELINE_CROSS_FEATURE]
print(f'\nFeature columns ({len(cols)}): {cols}')
print(f'\nMean QA scores: at={X_qa[:, 0].mean():.3f}  '
      f'isAt={X_qa[:, 4].mean():.3f}  '
      f'evidence={X_qa[:, 8].mean():.3f}')

Loading cached QA features from /content/HIPE/runs/qa_evidence_xlm_r_base_squad2.npz

Feature columns (15): ['qa_at_score', 'qa_at_has_answer', 'qa_at_span_length', 'qa_at_span_position', 'qa_isAt_score', 'qa_isAt_has_answer', 'qa_isAt_span_length', 'qa_isAt_span_position', 'qa_evidence_score', 'qa_evidence_has_answer', 'qa_evidence_span_length', 'qa_evidence_span_position', 'qa_at_isAt_score_gap', 'qa_max_score', 'qa_evidence_is_dateline']

Mean QA scores: at=0.343  isAt=0.530  evidence=0.663


### QA threshold-only ablation

Sanity check from the spec: classify using QA confidence alone and see
whether it reaches the ~0.50 global-score floor that justifies wiring the
features into the main classifier.

In [52]:
import numpy as np, pandas as pd
from sklearn.metrics import recall_score, classification_report

from hipe.subgroup_discovery import qa_threshold_classifier, QA_FEATURE_NAMES

at_idx   = QA_FEATURE_NAMES.index('qa_at_score')
isAt_idx = QA_FEATURE_NAMES.index('qa_isAt_score')

at_pred, isAt_pred = [], []
for row in X_qa:
    a, b = qa_threshold_classifier({
        'qa_at_score':   row[at_idx],
        'qa_isAt_score': row[isAt_idx],
    })
    at_pred.append(a); isAt_pred.append(b)
at_pred   = np.array(at_pred)
isAt_pred = np.array(isAt_pred)

y_at   = np.array([i.at   for i in insts])
y_isAt = np.array([i.isAt for i in insts])

# Restrict to the test split (the 188-instance evaluation universe).
y_at_test   = y_at[test_idx]
y_isAt_test = y_isAt[test_idx]

mr_at   = recall_score(y_at_test,   at_pred[test_idx],
                       average='macro', labels=['TRUE','PROBABLE','FALSE'])
mr_isAt = recall_score(y_isAt_test, isAt_pred[test_idx],
                       average='macro', labels=['TRUE','FALSE'])
print(f'QA-threshold-only  MR(at)   = {mr_at:.4f}')
print(f'                   MR(isAt) = {mr_isAt:.4f}')
print('\n at confusion:')
print(pd.crosstab(pd.Series(y_at_test, name='gold'),
                  pd.Series(at_pred[test_idx], name='pred'),
                  margins=True))

QA-threshold-only  MR(at)   = 0.3459
                   MR(isAt) = 0.4228

 at confusion:
pred      FALSE  PROBABLE  TRUE  All
gold                                
FALSE        16        37    51  104
PROBABLE      6         8     4   18
TRUE         10        27    29   66
All          32        72    84  188


In [60]:
import numpy as np
y_test = y[test_idx]
print('qa_at_score by gold label (test split, n=188):')
for lbl in ['FALSE', 'PROBABLE', 'TRUE']:
    s = X_qa[test_idx][y_test == lbl, 0]
    print(f'  {lbl:10s} n={(y_test==lbl).sum():3d}  '
          f'mean={s.mean():.3f}  median={np.median(s):.3f}  '
          f'q25={np.percentile(s,25):.3f}  q75={np.percentile(s,75):.3f}')

print('\nqa_isAt_score by gold label:')
for lbl in ['FALSE', 'TRUE']:
    s = X_qa[test_idx][np.array([i.isAt for i in insts])[test_idx] == lbl, 4]
    print(f'  {lbl:10s} n={(np.array([i.isAt for i in insts])[test_idx]==lbl).sum():3d}  '
          f'mean={s.mean():.3f}  median={np.median(s):.3f}')

qa_at_score by gold label (test split, n=188):
  FALSE      n=104  mean=0.387  median=0.293  q25=0.152  q75=0.536
  PROBABLE   n= 18  mean=0.236  median=0.159  q25=0.073  q75=0.230
  TRUE       n= 66  mean=0.355  median=0.262  q25=0.139  q75=0.583

qa_isAt_score by gold label:
  FALSE      n=150  mean=0.566  median=0.565
  TRUE       n= 38  mean=0.470  median=0.398


## Build SD-HQ / SD-HQS using the cached QA matrix

Drop the cached 15-d QA block straight into `build_sd_feature_matrix` —
no second GPU pass.

In [21]:
import numpy as np
from hipe.subgroup_discovery import build_sd_feature_matrix, QA_FEATURE_NAMES

# Re-load the spectral-eligible MASK cache to feed SD-HQS (pick whichever
# encoder cache you used in Cell 9; this matches the contrastive default).
mask_npz = sorted((PROJECT / 'runs').glob('mask_dbmdz_*_M2*.npz'))[0]
mask_emb = np.load(mask_npz)['mask_emb'].astype(np.float32)

X_hq, names_hq, meta_hq = build_sd_feature_matrix(
    insts, config='SD-HQ',
    qa_features=X_qa,
    verbose=True,
)
print(f'\nSD-HQ shape  : {X_hq.shape}')

X_hqs, names_hqs, meta_hqs = build_sd_feature_matrix(
    insts, mask_embeddings=mask_emb, config='SD-HQS',
    qa_features=X_qa,
    spectral_n_components=10, spectral_n_neighbors=15,
    verbose=True,
)
print(f'SD-HQS shape : {X_hqs.shape}')
print(f'Total feature dims by config: H=47, HQ={X_hq.shape[1]}, '
      f'HQS={X_hqs.shape[1]}')

  handcrafted block    : 47-d
  QA evidence (cached) : padded 14 -> 15-d (cross-check column missing in cache)
Config SD-HQ: 62 total features (rows: 1251)

SD-HQ shape  : (1251, 62)
  handcrafted block    : 47-d
  QA evidence (cached) : padded 14 -> 15-d (cross-check column missing in cache)
  spectral eigenvalues : [-0. -0.  0.  0.  0.  0.]
  spectral gaps        : [0. 0. 0. 0. 0.]
  suggested clusters   : 10
  eigenvector NMI(y)   : [0.005, 0.004, 0.006, 0.007, 0.005]
Config SD-HQS: 72 total features (rows: 1251)
SD-HQS shape : (1251, 72)
Total feature dims by config: H=47, HQ=62, HQS=72


## End-to-end RF comparison: SD-H vs SD-HQ

Same RF protocol as Cell D4 (188-instance test split), but now ablating the
QA block on top of the dateline-augmented handcrafted set.


In [24]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import recall_score

def macro_recall(X_train, X_test, y_train, y_test, labels):
    clf = RandomForestClassifier(
        n_estimators=300, class_weight='balanced',
        min_samples_leaf=3, random_state=42, n_jobs=-1,
    )
    clf.fit(X_train, y_train)
    return recall_score(y_test, clf.predict(X_test),
                        average='macro', labels=labels)

results = {}
for config_name, X_full in [('SD-H', X), ('SD-HQ', X_hq)]:
    results[config_name] = macro_recall(
        X_full[train_idx], X_full[test_idx],
        y[train_idx], y[test_idx],
        labels=['TRUE','PROBABLE','FALSE'],
    )
print('\n  Macro-Recall(at):')
for k, v in results.items():
    print(f'    {k:8s} : {v:.4f}')
print(f'    Δ HQ-H   : {results["SD-HQ"] - results["SD-H"]:+.4f}')


  Macro-Recall(at):
    SD-H     : 0.6140
    SD-HQ    : 0.5852
    Δ HQ-H   : -0.0288


### MCMC subgroup discovery on SD-HQ, target=PROBABLE

Builds SD-H *and* SD-HQ on the train split (so we run apples-to-apples and
both compete on the same MCMC budget), runs `MCMCSubgroupDiscovery` for
target=PROBABLE on each, and prints the top-10 patterns side-by-side. The
specific question we want answered: **does any QA feature appear in the
top SD-HQ subgroups, and in particular does the `qa_at_score ∈ [low, low]`
PROBABLE-marker pattern surface?**

In [ ]:
import time
from pathlib import Path
import numpy as np
import pandas as pd

from hipe.subgroup_discovery import (
    MCMCSubgroupDiscovery,
    build_sd_feature_matrix,
)

PROJECT = Path('/content/HIPE')

# Train-only filter (matches scripts/discover_probable_subgroups.py default).
ids_df = pd.read_csv(PROJECT / 'data' / 'v1_baseline_train_test_ids.csv',
                     dtype=str, keep_default_na=False)
at_df = ids_df[ids_df['task'] == 'at']
train_sids = set(at_df.loc[at_df['split'] == 'train', 'sample_id'])

train_idx_full = [k for k, i in enumerate(insts) if i.sample_id in train_sids]
insts_tr = [insts[k] for k in train_idx_full]
X_qa_tr  = X_qa[train_idx_full]
print(f'train rows: {len(insts_tr)}')

In [28]:


def run_sd(config, mask_embeddings=None, qa_features=None, target='PROBABLE'):
    X, names, meta = build_sd_feature_matrix(
        insts_tr,
        mask_embeddings=mask_embeddings,
        qa_features=qa_features,
        config=config,
        verbose=False,
    )
    y = np.array([i.at for i in insts_tr])
    sd = MCMCSubgroupDiscovery(
        feature_names=names, target_class=target,
        n_chains=10, n_steps=10000,
        nwracc_threshold=0.05,        # ← was 0.3; PROBABLE max is ~0.087 on this data
        redundancy_theta=0.5,
        top_k=10, min_support=2, random_state=42,
    )
    t0 = time.perf_counter()
    subgroups = sd.fit(X, y)
    print(f'{config:6s}  ({X.shape[1]:3d}-d, {(y == target).sum()} positives) -> '
          f'{len(subgroups)} subgroups in {time.perf_counter() - t0:.1f}s')
    return subgroups, names

print('\n--- SD-H baseline (no QA features), nwracc_threshold=0.05 ---')
sg_h, names_h = run_sd('SD-H')

print('\n--- SD-HQ (handcrafted + QA evidence block) ---')
sg_hq, names_hq = run_sd('SD-HQ', qa_features=X_qa_tr)


--- SD-H baseline (no QA features), nwracc_threshold=0.05 ---
SD-H    ( 47-d, 102 positives) -> 10 subgroups in 145.9s

--- SD-HQ (handcrafted + QA evidence block) ---
SD-HQ   ( 62-d, 102 positives) -> 0 subgroups in 187.8s


In [29]:
def fmt_top(subgroups, k=10):
    rows = []
    for j, sg in enumerate(subgroups[:k]):
        rows.append({
            'rank'    : j + 1,
            'NWRAcc'  : round(float(sg.nwracc), 3),
            'prec'    : round(float(sg.precision), 2),
            'sup_pos/sup': f'{sg.support_pos}/{sg.support}',
            '|active|': sg.n_active(),
            'pattern' : sg.pattern_desc,
        })
    return pd.DataFrame(rows)

with pd.option_context('display.max_colwidth', 110, 'display.width', 220):
    print('\nSD-H top 10 (PROBABLE):')
    print(fmt_top(sg_h).to_string(index=False))
    print('\nSD-HQ top 10 (PROBABLE):')
    print(fmt_top(sg_hq).to_string(index=False))


SD-H top 10 (PROBABLE):
 rank  NWRAcc  prec sup_pos/sup  |active|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

In [30]:
# Did any QA feature surface in the SD-HQ top patterns?
qa_hits = []
for j, sg in enumerate(sg_hq):
    qa_in_pattern = [names_hq[k] for k in np.where(sg.active)[0]
                     if names_hq[k].startswith('qa_')]
    if qa_in_pattern:
        qa_hits.append({
            'rank'     : j + 1,
            'NWRAcc'   : round(float(sg.nwracc), 3),
            'prec'     : round(float(sg.precision), 2),
            'qa_features_used': qa_in_pattern,
            'pattern'  : sg.pattern_desc,
        })

if qa_hits:
    print(f'{len(qa_hits)} of the top {len(sg_hq)} SD-HQ subgroups use a QA feature:')
    with pd.option_context('display.max_colwidth', 140, 'display.width', 260):
        print(pd.DataFrame(qa_hits).to_string(index=False))
else:
    print('No QA features appear in the top SD-HQ subgroups — the asymmetric '
          'PROBABLE-low-QA signal did NOT survive MCMC ranking under the '
          'NWRAcc>=0.3 / redundancy threshold.')

No QA features appear in the top SD-HQ subgroups — the asymmetric PROBABLE-low-QA signal did NOT survive MCMC ranking under the NWRAcc>=0.3 / redundancy threshold.


In [31]:
def run_sd_big(config, qa_features=None, target='PROBABLE',
               n_steps=30_000, n_chains=10):
    X, names, _ = build_sd_feature_matrix(
        insts_tr, qa_features=qa_features, config=config, verbose=False,
    )
    y = np.array([i.at for i in insts_tr])
    sd = MCMCSubgroupDiscovery(
        feature_names=names, target_class=target,
        n_chains=n_chains, n_steps=n_steps,
        nwracc_threshold=0.05, redundancy_theta=0.5,
        top_k=10, min_support=2, random_state=42,
    )
    t0 = time.perf_counter()
    sg = sd.fit(X, y)
    print(f'{config:6s}  ({X.shape[1]:3d}-d, n_steps={n_steps:>6d}) -> '
          f'{len(sg)} subgroups in {time.perf_counter() - t0:.1f}s')
    return sg, names

print('\n--- SD-HQ with 3× MCMC budget ---')
sg_hq2, names_hq2 = run_sd_big('SD-HQ', qa_features=X_qa_tr, n_steps=30_000)


--- SD-HQ with 3× MCMC budget ---
SD-HQ   ( 62-d, n_steps= 30000) -> 0 subgroups in 550.7s


In [32]:
# Did any QA feature surface in the SD-HQ top patterns?
qa_hits2 = []
for j, sg in enumerate(sg_hq2):
    qa_in_pattern = [names_hq2[k] for k in np.where(sg.active)[0]
                     if names_hq2[k].startswith('qa_')]
    if qa_in_pattern:
        qa_hits2.append({
            'rank'     : j + 1,
            'NWRAcc'   : round(float(sg.nwracc), 3),
            'prec'     : round(float(sg.precision), 2),
            'qa_features_used': qa_in_pattern,
            'pattern'  : sg.pattern_desc,
        })

if qa_hits2:
    print(f'{len(qa_hits2)} of the top {len(sg_hq2)} SD-HQ subgroups use a QA feature:')
    with pd.option_context('display.max_colwidth', 140, 'display.width', 260):
        print(pd.DataFrame(qa_hits2).to_string(index=False))
else:
    print('No QA features appear in the top SD-HQ subgroups — the asymmetric '
          'PROBABLE-low-QA signal did NOT survive MCMC ranking under the '
          'NWRAcc>=0.3 / redundancy threshold.')

No QA features appear in the top SD-HQ subgroups — the asymmetric PROBABLE-low-QA signal did NOT survive MCMC ranking under the NWRAcc>=0.3 / redundancy threshold.


In [33]:
# Diagnostic: did MCMC explore anything at all in SD-HQ, or really nothing?
def run_sd_floor(threshold):
    X, names, _ = build_sd_feature_matrix(
        insts_tr, qa_features=X_qa_tr, config='SD-HQ', verbose=False,
    )
    y = np.array([i.at for i in insts_tr])
    sd = MCMCSubgroupDiscovery(
        feature_names=names, target_class='PROBABLE',
        n_chains=10, n_steps=10_000,
        nwracc_threshold=threshold,
        redundancy_theta=0.5,
        top_k=20, min_support=2, random_state=42,
    )
    t0 = time.perf_counter()
    sg = sd.fit(X, y)
    print(f'SD-HQ thr={threshold:>6.4f}  -> {len(sg)} subgroups in '
          f'{time.perf_counter() - t0:.1f}s'
          + (f'  top NWRAcc={sg[0].nwracc:.4f}' if sg else ''))
    return sg

for thr in (0.05, 0.02, 0.005, 0.001):
    run_sd_floor(thr)

SD-HQ thr=0.0500  -> 0 subgroups in 175.8s
SD-HQ thr=0.0200  -> 20 subgroups in 175.2s  top NWRAcc=0.0294
SD-HQ thr=0.0050  -> 20 subgroups in 234.1s  top NWRAcc=0.0294
SD-HQ thr=0.0010  -> 20 subgroups in 239.2s  top NWRAcc=0.0294


In [34]:
# Capture the thr=0.02 patterns (the floor where SD-HQ first surfaces signal).
def run_sd_capture(threshold=0.02):
    X, names, _ = build_sd_feature_matrix(
        insts_tr, qa_features=X_qa_tr, config='SD-HQ', verbose=False,
    )
    y = np.array([i.at for i in insts_tr])
    sd = MCMCSubgroupDiscovery(
        feature_names=names, target_class='PROBABLE',
        n_chains=10, n_steps=10_000,
        nwracc_threshold=threshold, redundancy_theta=0.5,
        top_k=20, min_support=2, random_state=42,
    )
    return sd.fit(X, y), names

sg_hq_floor, names_hq_floor = run_sd_capture(threshold=0.02)
print(f'captured {len(sg_hq_floor)} patterns')

captured 20 patterns


In [35]:
import numpy as np

def real_constraints(sg, names):
    """Return only the features whose bounds actually narrow the [0,1] cube."""
    bounds = sg.bounds
    out = []
    for k, (lo, hi) in enumerate(bounds):
        if not sg.active[k]:
            continue
        # Skip fully permissive ranges.
        if lo <= 0.0 + 1e-6 and hi >= 1.0 - 1e-6:
            continue
        out.append((names[k], float(lo), float(hi)))
    return out

print(f'\nSD-HQ top patterns at NWRAcc ≥ 0.02 (n={len(sg_hq_floor)}):\n')
qa_used_count = 0
for j, sg in enumerate(sg_hq_floor[:10]):
    constraints = real_constraints(sg, names_hq_floor)
    qa_constraints = [c for c in constraints if c[0].startswith('qa_')]
    if qa_constraints:
        qa_used_count += 1
    tag = '  [QA!]' if qa_constraints else ''
    print(f'[{j+1:2d}] NWRAcc={sg.nwracc:.4f}  prec={sg.precision:.2f}  '
          f'sup={sg.support_pos}/{sg.support}  ({len(constraints)} real constraints){tag}')
    for name, lo, hi in constraints:
        flag = ' ←' if name.startswith('qa_') else ''
        print(f'      {name:35s}  [{lo:6.3f}, {hi:6.3f}]{flag}')

print(f'\n{qa_used_count} of top 10 patterns use a QA feature as a real constraint')


SD-HQ top patterns at NWRAcc ≥ 0.02 (n=20):

[ 1] NWRAcc=0.0294  prec=1.00  sup=3/3  (49 real constraints)  [QA!]
      verb_is_present                      [ 0.000,  0.000]
      verb_is_negated                      [ 0.000,  0.000]
      verb_is_future                       [ 0.000,  0.000]
      sentence_position_norm               [ 0.000,  0.180]
      signal_negation                      [ 0.000,  0.000]
      signal_present                       [ 0.000,  0.000]
      has_timex_in_window                  [ 0.000,  0.000]
      nearest_timex_distance_norm          [ 0.000,  0.000]
      person_is_deceased                   [ 0.000,  0.000]
      ocr_quality                          [ 0.984,  1.000]
      entity_char_distance                 [ 0.682,  0.964]
      entities_adjacent                    [ 0.000,  0.000]
      has_preposition_link                 [ 0.000,  0.000]
      has_role_title                       [ 0.000,  0.000]
      has_hedging                          [ 

In [36]:
# Match the conventional SD literature default: min_support >= 10% of positives.
# With 102 PROBABLE positives, that's >= 10.
def run_sd_minsup(config, qa_features=None, min_support=10):
    X, names, _ = build_sd_feature_matrix(
        insts_tr, qa_features=qa_features, config=config, verbose=False,
    )
    y = np.array([i.at for i in insts_tr])
    sd = MCMCSubgroupDiscovery(
        feature_names=names, target_class='PROBABLE',
        n_chains=10, n_steps=10_000,
        nwracc_threshold=0.02, redundancy_theta=0.5,
        top_k=10, min_support=min_support, random_state=42,
    )
    t0 = time.perf_counter()
    sg = sd.fit(X, y)
    print(f'{config:6s}  min_support={min_support:>3d}  -> {len(sg)} subgroups '
          f'({time.perf_counter() - t0:.1f}s)'
          + (f'  top NWRAcc={sg[0].nwracc:.4f}' if sg else ''))
    return sg, names

print('--- SD-H, min_support=10 ---')
sg_h_ms, names_h_ms   = run_sd_minsup('SD-H')

print('--- SD-HQ, min_support=10 ---')
sg_hq_ms, names_hq_ms = run_sd_minsup('SD-HQ', qa_features=X_qa_tr)

--- SD-H, min_support=10 ---
SD-H    min_support= 10  -> 10 subgroups (140.9s)  top NWRAcc=0.0781
--- SD-HQ, min_support=10 ---
SD-HQ   min_support= 10  -> 0 subgroups (169.6s)


In [38]:
print(f'\nSD-HQ top patterns at NWRAcc ≥ 0.02 (n={len(sg_hq_ms)}):\n')
qa_used_count = 0
for j, sg in enumerate(sg_hq_ms[:10]):
    constraints = real_constraints(sg, names_hq_ms)
    qa_constraints = [c for c in constraints if c[0].startswith('qa_')]
    if qa_constraints:
        qa_used_count += 1
    tag = '  [QA!]' if qa_constraints else ''
    print(f'[{j+1:2d}] NWRAcc={sg.nwracc:.4f}  prec={sg.precision:.2f}  '
          f'sup={sg.support_pos}/{sg.support}  ({len(constraints)} real constraints){tag}')
    for name, lo, hi in constraints:
        flag = ' ←' if name.startswith('qa_') else ''
        print(f'      {name:35s}  [{lo:6.3f}, {hi:6.3f}]{flag}')

print(f'\n{qa_used_count} of top 10 patterns use a QA feature as a real constraint')


SD-HQ top patterns at NWRAcc ≥ 0.02 (n=0):


0 of top 10 patterns use a QA feature as a real constraint


## Verify the Dataset

In [19]:
# verify the dataset
import pathlib

required = [
    'data/dataset_reference.jsonl',
    'data/v1_baseline_train_test_ids.csv',
]
for rel in required:
    p = pathlib.Path('/content/HIPE') / rel
    print(f"{'OK ' if p.exists() else 'MISSING'}  {rel}  "
          f"({p.stat().st_size/1e6:.1f} MB)" if p.exists() else f"MISSING  {rel}")

OK   data/dataset_reference.jsonl  (7.8 MB)
OK   data/v1_baseline_train_test_ids.csv  (0.6 MB)


## Phase 0: M2 baseline + diagnostics

In [20]:
!python scripts/extract_mask_embeddings.py \
    --template M2 --field context \
    --max-seq-length 256 --batch-size 32

Loading dataset /content/HIPE/data/dataset_reference.jsonl
  1251 instances
Loading encoder dbmdz/bert-base-historic-multilingual-cased (template=M2, field=context, layers=(-1,))
config.json: 100% 561/561 [00:00<00:00, 2.64MB/s]
tokenizer_config.json: 100% 83.0/83.0 [00:00<00:00, 544kB/s]
vocab.txt: 212kB [00:00, 12.7MB/s]
model.safetensors: 100% 445M/445M [00:02<00:00, 183MB/s]
Loading weights: 100% 199/199 [00:00<00:00, 943.64it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: dbmdz/bert-base-historic-multilingual-cased
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions

In [25]:
!python scripts/extract_mask_embeddings.py --template M2 --field context --layers -1 -4 -7

Loading dataset /content/HIPE/data/dataset_reference.jsonl
  1251 instances
Loading encoder dbmdz/bert-base-historic-multilingual-cased (template=M2, field=context, layers=(-1, -4, -7))
config.json: 100% 561/561 [00:00<00:00, 3.37MB/s]
tokenizer_config.json: 100% 83.0/83.0 [00:00<00:00, 676kB/s]
vocab.txt: 212kB [00:00, 12.8MB/s]
model.safetensors: 100% 445M/445M [00:06<00:00, 67.1MB/s]
Loading weights: 100% 199/199 [00:00<00:00, 1313.14it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: dbmdz/bert-base-historic-multilingual-cased
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 
bert.embeddings.position_ids               | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 
cls.se

In [26]:
import numpy as np
z = np.load('runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2_L-1_-4_-7.npz')
print('has_timex count:', int(z['temporal'][:,10].sum()))

has_timex count: 101


In [20]:
#import numpy as np, os, datetime
#p = '/content/HIPE/runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2.npz'
#print('mtime:', datetime.datetime.fromtimestamp(os.path.getmtime(p)))
#z = np.load(p)
# col 10 = has_timex_in_window per hipe.features.temporal.TEMPORAL_FEATURE_NAMES
#print('has_timex_in_window column count of 1.0s:', int(z['temporal'][:,10].sum()))



mtime: 2026-05-01 07:16:48
has_timex_in_window column count of 1.0s: 101


In [27]:
!python scripts/phase0_mask_diagnostics.py \
    --npz runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2.npz \
    --skip-umap   # drop this flag if you want the UMAP plots (~2 min)

Loading runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2.npz
  mask_emb       : (1251, 768)
  e1_emb         : (1251, 768)
  e2_emb         : (1251, 768)
  concat_emb     : (1251, 2304)
  temporal       : (1251, 15)
  handcrafted    : (1251, 36)
  at unique      : [np.str_('FALSE'), np.str_('PROBABLE'), np.str_('TRUE')]
  isAt unique    : [np.str_('FALSE'), np.str_('TRUE')]
  languages      : [np.str_('de'), np.str_('en'), np.str_('fr')]

[1/3] Computing PCA(2) of mask_emb ...
  explained variance: [0.23980038 0.17400046]
[2/3] UMAP skipped (--skip-umap)
[3/3] Silhouette scores
  silhouette(at)   = -0.0118
  silhouette(isAt) = 0.0106

CV baselines (5-fold stratified, macro-recall)

--- target: at ---

  C1_mask_LR [target=at]: macro-recall = 0.5564 ± 0.0543  (n=1251, dim=768)
      FALSE         prec=0.739  recall=0.693  n=690.0
      PROBABLE      prec=0.320  recall=0.342  n=120.0
      TRUE          prec=0.588  recall=0.635  n=441.0

  C4_mask+e1+e2+temporal_LR [target=at]: m

In [28]:
import json, pathlib
res = json.loads(pathlib.Path('runs/phase0_mask_diag/results.json').read_text())
print(json.dumps(res['gate'], indent=2))

{
  "at": {
    "mask_score": 0.5564342743507373,
    "handcrafted_score": 0.5671671527191802,
    "delta": -0.010732878368442833,
    "decision": "CONDITIONAL",
    "spec_floor": 0.59,
    "passes_spec_floor": false
  },
  "isAt": {
    "mask_score": 0.6898853380296679,
    "handcrafted_score": 0.6776871152902081,
    "delta": 0.012198222739459808,
    "decision": "CONDITIONAL",
    "spec_floor": 0.68,
    "passes_spec_floor": true
  }
}


## Phase 1a: extract all five templates on hmBERT (multi-layer)

In [29]:
!python scripts/run_mask_template_encoder_grid.py \
    --templates M1 M2 M3 M4 M5 \
    --encoders dbmdz/bert-base-historic-multilingual-cased \
    --layers -1 -4 -7 \
    --max-seq-length 256 --batch-size 32

Loading dataset /content/HIPE/data/dataset_reference.jsonl
  1251 instances
Pre-computing handcrafted + temporal feature matrices ...

Grid: 5 cells (1 encoder(s) × 5 template(s))

[1/5] SKIP dbmdz/bert-base-historic-multilingual-cased × M1  (cache exists, 35.7 MB)

[2/5] SKIP dbmdz/bert-base-historic-multilingual-cased × M2  (cache exists, 35.7 MB)

[3/5] SKIP dbmdz/bert-base-historic-multilingual-cased × M3  (cache exists, 35.7 MB)

[4/5] SKIP dbmdz/bert-base-historic-multilingual-cased × M4  (cache exists, 35.7 MB)

[5/5] SKIP dbmdz/bert-base-historic-multilingual-cased × M5  (cache exists, 35.7 MB)

Grid done in 0.0 min — ok=0 skipped=5 failed=0
Summary: /content/HIPE/runs/mask_grid_extraction_summary.json


In [30]:
# inspect the resulting cache index
!ls -la runs/mask_*.npz

-rw------- 1 root root 35720576 Apr 30 22:39 runs/mask_dbmdz_bert_base_historic_multilingual_cased_M1_L-1_-4_-7.npz
-rw------- 1 root root 35774336 Apr 30 22:43 runs/mask_dbmdz_bert_base_historic_multilingual_cased_M1_L-1_-4_-7_spec10.npz
-rw------- 1 root root 35720576 May  1 14:09 runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2_L-1_-4_-7.npz
-rw------- 1 root root 35774436 Apr 30 22:43 runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2_L-1_-4_-7_spec10.npz
-rw------- 1 root root 28034416 May  1 07:16 runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2.npz
-rw------- 1 root root 28088284 May  1 07:20 runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2_spec10.npz
-rw------- 1 root root 35720576 Apr 30 22:40 runs/mask_dbmdz_bert_base_historic_multilingual_cased_M3_L-1_-4_-7.npz
-rw------- 1 root root 35774404 Apr 30 22:43 runs/mask_dbmdz_bert_base_historic_multilingual_cased_M3_L-1_-4_-7_spec10.npz
-rw------- 1 root root 35720576 Apr 30 22:40 runs/mask_dbmdz_ber

## Phase 1b: encoder comparison on M2

In [31]:
# XLM-R-base (multilingual baseline; ~12 min on T4)
!python scripts/run_mask_template_encoder_grid.py \
    --templates M2 \
    --encoders xlm-roberta-base \
    --layers -1 -4 -7 \
    --max-seq-length 256 --batch-size 32

Loading dataset /content/HIPE/data/dataset_reference.jsonl
  1251 instances
Pre-computing handcrafted + temporal feature matrices ...

Grid: 1 cells (1 encoder(s) × 1 template(s))

[1/1] SKIP xlm-roberta-base × M2  (cache exists, 35.7 MB)

Grid done in 0.0 min — ok=0 skipped=1 failed=0
Summary: /content/HIPE/runs/mask_grid_extraction_summary.json


In [32]:
# mGTE (long-context; ~15 min on T4) — context fits the full 8k window so
# we deliberately use a longer max-seq-length here.
!python scripts/run_mask_template_encoder_grid.py \
    --templates M2 \
    --encoders Alibaba-NLP/gte-multilingual-base \
    --layers -1 -4 -7 \
    --max-seq-length 512 --batch-size 16

Loading dataset /content/HIPE/data/dataset_reference.jsonl
  1251 instances
Pre-computing handcrafted + temporal feature matrices ...

Grid: 1 cells (1 encoder(s) × 1 template(s))

[1/1] EXTRACT  encoder=Alibaba-NLP/gte-multilingual-base  template=M2  layers=(-1, -4, -7)
config.json: 1.43kB [00:00, 3.07MB/s]
Alibaba-NLP/new-impl You can inspect the repository content at https://hf.co/Alibaba-NLP/gte-multilingual-base.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] You are using a model of type new to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
tokenizer_config.json: 1.15kB [00:00, 3.61MB/s]
tokenizer.json: 100% 17.1M/17.1M [00:00<00:00, 27.5MB/s]
special_tokens_map.json: 100% 964/964 [00:00<00:00, 5.52MB/s]
Alibaba-NLP/new-impl You can inspect the repository content at https://hf.co/Alibaba-NLP/gte-multilingual-base.
You can avoid this prompt 

In [33]:
# XLM-R-large (heavier; ~25 min on T4, may OOM at batch_size=16 — drop to 8)
!python scripts/run_mask_template_encoder_grid.py \
    --templates M2 \
    --encoders xlm-roberta-large \
    --layers -1 -4 -7 \
    --max-seq-length 256 --batch-size 8

Loading dataset /content/HIPE/data/dataset_reference.jsonl
  1251 instances
Pre-computing handcrafted + temporal feature matrices ...

Grid: 1 cells (1 encoder(s) × 1 template(s))

[1/1] SKIP xlm-roberta-large × M2  (cache exists, 47.2 MB)

Grid done in 0.0 min — ok=0 skipped=1 failed=0
Summary: /content/HIPE/runs/mask_grid_extraction_summary.json


## Phase 2: spectral features

For each cache, build a Laplacian eigenmap on the **same set of instances** (transductive — appropriate when train + test share a single closed pool). The augmented file is written next to the original with a `_spec<k>` suffix; `mask_grid_eval.py` picks them up automatically.

In [34]:
!for f in runs/mask_*.npz; do \
    [[ "$f" == *_spec* ]] && continue; \
    echo "==> $f"; \
    python scripts/extract_spectral_features.py \
        --npz "$f" \
        --base mask_emb_layers \
        --n-components 10 \
        --n-neighbors 20; \
done

==> runs/mask_dbmdz_bert_base_historic_multilingual_cased_M1_L-1_-4_-7.npz
Loading runs/mask_dbmdz_bert_base_historic_multilingual_cased_M1_L-1_-4_-7.npz
  base shape: (1251, 2304)  metric=cosine  k=20
Computing spectral features ...
  features shape: (1251, 10)
  eigenvalues  : [0.0572 0.068  0.0725 0.0833 0.091  0.1213 0.1316 0.1428 0.1465 0.151 ]
  NMI(at)  per eigenvector : ['0.005', '0.002', '0.002', '0.000', '0.000', '0.002', '0.004', '0.005', '0.003', '0.003']
  NMI(isAt) per eigenvector: ['0.006', '0.002', '0.003', '0.005', '0.004', '0.000', '0.000', '0.002', '0.001', '0.001']
Wrote runs/mask_dbmdz_bert_base_historic_multilingual_cased_M1_L-1_-4_-7_spec10.npz  (35.8 MB)
==> runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2_L-1_-4_-7.npz
Loading runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2_L-1_-4_-7.npz
  base shape: (1251, 2304)  metric=cosine  k=20
Computing spectral features ...
  features shape: (1251, 10)
  eigenvalues  : [-5.8711e-09  2.3696e-07  2.7283e

Sanity check NMI (eigenvector vs label) for one cache. We resolve the path against the absolute project root (set in Cell 3 via `os.chdir`), and we glob-match `*_spec*.npz` so this works regardless of which encoder/template/layer combination Cell 9 produced — it just picks the first multi-layer hmBERT spectral cache it finds.


In [35]:
# sanity check
import numpy as np, json
from pathlib import Path

PROJECT = Path('/content/HIPE')
runs_dir = PROJECT / 'runs'

# Prefer the multi-layer hmBERT spectral cache; fall back to any spectral cache.
candidates = sorted(runs_dir.glob('mask_dbmdz_*_M2_L*_spec*.npz')) \
          or sorted(runs_dir.glob('mask_*_spec*.npz'))
if not candidates:
    raise FileNotFoundError(
        f"No *_spec*.npz cache under {runs_dir}. Did Cell 11 finish?\n"
        f"runs/ contents: {[p.name for p in runs_dir.glob('*.npz')]}"
    )
cache_path = candidates[0]
print('Using cache:', cache_path)

z = np.load(cache_path, allow_pickle=True)
meta = json.loads(z['_meta_spectral'].item())
print('eigenvalues :', np.round(meta['eigenvalues'], 4))
print('NMI(at)     :', np.round(meta['nmi_at'], 3))
print('NMI(isAt)   :', np.round(meta['nmi_isAt'], 3))

Using cache: /content/HIPE/runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2_L-1_-4_-7_spec10.npz
eigenvalues : [-0.      0.      0.      0.0001  0.0012  0.0021  0.0025  0.0062  0.0066
  0.0072]
NMI(at)     : [0.005 0.005 0.007 0.012 0.013 0.01  0.001 0.002 0.004 0.003]
NMI(isAt)   : [0.001 0.001 0.    0.001 0.002 0.002 0.    0.005 0.    0.   ]


A high NMI on any of the leading eigenvectors means the spectral features are likely useful as classifier inputs.

## Phase 3: score every cache against the official metric

This is the workhorse cell. It loads every `runs/mask_*.npz`, trains LR / RF on the at-task train slice, predicts on the at-task test slice, and writes `_predictions.jsonl` + `_report.json` per cell into `logs/ablations/`. Same format as the LLM runs, so the cross-config disagreement matrix and final report pick them up automatically.

In [36]:
!python scripts/mask_grid_eval.py \
    --task at \
    --feature-sets mask mask_layers concat_t concat_l_t \
                   mask_at mask_isAt mask_multi \
    --include-spectral \
    --include-handcrafted

Discovered 16 caches:
  mask_dbmdz_bert_base_historic_multilingual_cased_M1_L-1_-4_-7.npz  (35.7 MB)
  mask_dbmdz_bert_base_historic_multilingual_cased_M1_L-1_-4_-7_spec10.npz  (35.8 MB)
  mask_dbmdz_bert_base_historic_multilingual_cased_M2.npz  (28.0 MB)
  mask_dbmdz_bert_base_historic_multilingual_cased_M2_L-1_-4_-7.npz  (35.7 MB)
  mask_dbmdz_bert_base_historic_multilingual_cased_M2_L-1_-4_-7_spec10.npz  (35.8 MB)
  mask_dbmdz_bert_base_historic_multilingual_cased_M2_spec10.npz  (28.1 MB)
  mask_dbmdz_bert_base_historic_multilingual_cased_M3_L-1_-4_-7.npz  (35.7 MB)
  mask_dbmdz_bert_base_historic_multilingual_cased_M3_L-1_-4_-7_spec10.npz  (35.8 MB)
  mask_dbmdz_bert_base_historic_multilingual_cased_M4_L-1_-4_-7.npz  (35.7 MB)
  mask_dbmdz_bert_base_historic_multilingual_cased_M4_L-1_-4_-7_spec10.npz  (35.8 MB)
  mask_dbmdz_bert_base_historic_multilingual_cased_M5_L-1_-4_-7.npz  (35.7 MB)
  mask_dbmdz_bert_base_historic_multilingual_cased_M5_L-1_-4_-7_spec10.npz  (35.8 MB)
  mask_x

The script prints a top-15 leaderboard at the end, e.g.:

```text
==============================================================================
Top 15 cells by GlobalScore (task=at)
==============================================================================
experiment_id                                                global   MR(at)  MR(isAt)
T1.4or5_mask_grid_mask_dbmdz..._M2_L_1__4__7_concat_l_t_at  0.5950  0.6321  0.5579
T1.4or5_mask_grid_mask_xlm_roberta_base_M2_concat_t_at     0.5810  0.6024  0.5596
...
```

Open the aggregate JSON for the full table:

In [37]:
import json, pandas as pd
from pathlib import Path

PROJECT = Path('/content/HIPE')
rows = json.loads((PROJECT / 'runs' / 'mask_grid_eval' / 'summary.json').read_text())['rows']
df = pd.DataFrame(rows).sort_values('global_score', ascending=False)
df[['experiment_id', 'feature_set', 'target', 'input_dim',
    'global_score', 'macro_recall_at', 'macro_recall_isAt']].head(20)

,experiment_id,feature_set,target,input_dim,global_score,macro_recall_at,macro_recall_isAt
0,T1.4or5_mask_grid_handcrafted_rf_at_at-test,handcrafted,at,36,0.581342,0.662685,0.500000
1,T1.4or5_mask_grid_mask_dbmdz_bert_base_histori...,mask,at,768,0.573653,0.647306,0.500000
2,T1.4or5_mask_grid_mask_dbmdz_bert_base_histori...,mask,at,768,0.573653,0.647306,0.500000
3,T1.4or5_mask_grid_mask_xlm_roberta_large_M2_L-...,concat_l_t,at,5135,0.560865,0.621730,0.500000
4,T1.4or5_mask_grid_mask_xlm_roberta_large_M2_L-...,concat_l_t,at,5135,0.560865,0.621730,0.500000
5,T1.4or5_mask_grid_mask_dbmdz_bert_base_histori...,concat_t,isAt,2319,0.559386,0.333333,0.785439
6,T1.4or5_mask_grid_mask_dbmdz_bert_base_histori...,concat_t,isAt,2319,0.559386,0.333333,0.785439
7,T1.4or5_mask_grid_mask_dbmdz_bert_base_histori...,mask_layers,at,2304,0.555976,0.611953,0.500000
8,T1.4or5_mask_grid_mask_dbmdz_bert_base_histori...,mask_layers,at,2304,0.555976,0.611953,0.500000
9,T1.4or5_mask_grid_mask_dbmdz_bert_base_histori...,concat_l_t,at,3855,0.555054,0.610107,0.500000


## Phase 4: contrastive training (MLP + ordinal/SupCon)


Pick the strongest cache from Cell 12 (typically the multi-layer hmBERT one) and train the joint head:

In [38]:
from pathlib import Path

PROJECT = Path('/content/HIPE')
runs_dir = PROJECT / 'runs'

# Prefer the multi-layer hmBERT cache; fall back to the single-layer hmBERT one.
candidates = (
    sorted(runs_dir.glob('mask_dbmdz_*_M2_L*.npz'))
    or sorted(runs_dir.glob('mask_dbmdz_*_M2.npz'))
)
candidates = [p for p in candidates if '_spec' not in p.name]  # base cache, not spectral
if not candidates:
    raise FileNotFoundError(
        f'No hmBERT M2 cache under {runs_dir}. Run Cell 9 first.\n'
        f"runs/ contents: {[p.name for p in runs_dir.glob('*.npz')]}"
    )
CACHE = candidates[0]
FEATURE_SET = 'concat_l_t' if '_L' in CACHE.name else 'concat_t'
print(f'Cache       : {CACHE}')
print(f'Feature set : {FEATURE_SET}')

Cache       : /content/HIPE/runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2_L-1_-4_-7.npz
Feature set : concat_l_t


In [33]:
!python scripts/train_mask_contrastive.py \
    --npz "$CACHE" --feature-set "$FEATURE_SET" \
    --epochs 25 --alpha 0.7 \
    --contrastive-at ordinal --contrastive-isAt supcon \
    --val-fraction 0.1 --patience 6

Loading cache /content/HIPE/runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2_L-1_-4_-7.npz
  X shape           : (1251, 3855)
  feature set       : concat_l_t
  template / model  : M2 / dbmdz/bert-base-historic-multilingual-cased
  train (matched)   : 1063
  test  (matched)   : 188
  val carved        : 107
  train (after val) : 956

Training: epochs=25 alpha=0.7 contrastive(at)=ordinal contrastive(isAt)=supcon k_per_class=16
  epoch   0  loss=2.2569  val_global=0.4617  val_at=0.3333  val_isAt=0.5900
  epoch   1  loss=1.9608  val_global=0.5164  val_at=0.4146  val_isAt=0.6182
  epoch   2  loss=1.7296  val_global=0.5585  val_at=0.4941  val_isAt=0.6229
  epoch   3  loss=1.5371  val_global=0.6309  val_at=0.5750  val_isAt=0.6868
  epoch   4  loss=1.4333  val_global=0.6600  val_at=0.6434  val_isAt=0.6766
  epoch   5  loss=1.3380  val_global=0.6697  val_at=0.6572  val_isAt=0.6823
  epoch   6  loss=1.2813  val_global=0.6395  val_at=0.5735  val_isAt=0.7054
  epoch   7  loss=1.2240  val_

Useful ablations (all idempotent, ~2 min each):

In [34]:
# CE-only baseline (no contrastive contribution)
!python scripts/train_mask_contrastive.py \
    --npz "$CACHE" --feature-set "$FEATURE_SET" \
    --alpha 1.0 --contrastive-at none --contrastive-isAt none \
    --experiment-id T1.4or5_mask_contrastive_CEonly_at-test


Loading cache /content/HIPE/runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2_L-1_-4_-7.npz
  X shape           : (1251, 3855)
  feature set       : concat_l_t
  template / model  : M2 / dbmdz/bert-base-historic-multilingual-cased
  train (matched)   : 1063
  test  (matched)   : 188
  val carved        : 107
  train (after val) : 956

Training: epochs=20 alpha=1.0 contrastive(at)=none contrastive(isAt)=none k_per_class=16
  epoch   0  loss=1.3928  val_global=0.4788  val_at=0.3509  val_isAt=0.6067
  epoch   1  loss=1.0043  val_global=0.4897  val_at=0.3807  val_isAt=0.5987
  epoch   2  loss=0.7050  val_global=0.5506  val_at=0.4783  val_isAt=0.6229
  epoch   3  loss=0.4901  val_global=0.6474  val_at=0.6182  val_isAt=0.6766
  epoch   4  loss=0.3737  val_global=0.6506  val_at=0.6283  val_isAt=0.6729
  epoch   5  loss=0.2697  val_global=0.6276  val_at=0.6120  val_isAt=0.6433
  epoch   6  loss=0.2113  val_global=0.6273  val_at=0.5622  val_isAt=0.6924
  epoch   7  loss=0.1506  val_globa

In [35]:
# SupCon on at (vs the ordinal default)
!python scripts/train_mask_contrastive.py \
    --npz "$CACHE" --feature-set "$FEATURE_SET" \
    --contrastive-at supcon --contrastive-isAt supcon \
    --experiment-id T1.4or5_mask_contrastive_supcon_at-test


Loading cache /content/HIPE/runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2_L-1_-4_-7.npz
  X shape           : (1251, 3855)
  feature set       : concat_l_t
  template / model  : M2 / dbmdz/bert-base-historic-multilingual-cased
  train (matched)   : 1063
  test  (matched)   : 188
  val carved        : 107
  train (after val) : 956

Training: epochs=20 alpha=0.7 contrastive(at)=supcon contrastive(isAt)=supcon k_per_class=16
  epoch   0  loss=3.3510  val_global=0.4617  val_at=0.3333  val_isAt=0.5900
  epoch   1  loss=3.0484  val_global=0.4744  val_at=0.3668  val_isAt=0.5820
  epoch   2  loss=2.8015  val_global=0.5540  val_at=0.4916  val_isAt=0.6165
  epoch   3  loss=2.5967  val_global=0.6326  val_at=0.5950  val_isAt=0.6701
  epoch   4  loss=2.4729  val_global=0.6700  val_at=0.6634  val_isAt=0.6766
  epoch   5  loss=2.3694  val_global=0.6621  val_at=0.6383  val_isAt=0.6859
  epoch   6  loss=2.2994  val_global=0.6265  val_at=0.5346  val_isAt=0.7184
  epoch   7  loss=2.2343  val_g

In [36]:
# Aggressive ordinal margin
!python scripts/train_mask_contrastive.py \
    --npz "$CACHE" --feature-set "$FEATURE_SET" \
    --contrastive-at ordinal --base-margin 1.0 \
    --experiment-id T1.4or5_mask_contrastive_ordinal_m1_at-test

Loading cache /content/HIPE/runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2_L-1_-4_-7.npz
  X shape           : (1251, 3855)
  feature set       : concat_l_t
  template / model  : M2 / dbmdz/bert-base-historic-multilingual-cased
  train (matched)   : 1063
  test  (matched)   : 188
  val carved        : 107
  train (after val) : 956

Training: epochs=20 alpha=0.7 contrastive(at)=ordinal contrastive(isAt)=supcon k_per_class=16
  epoch   0  loss=2.5167  val_global=0.4700  val_at=0.3333  val_isAt=0.6067
  epoch   1  loss=2.2304  val_global=0.5031  val_at=0.3844  val_isAt=0.6219
  epoch   2  loss=2.0014  val_global=0.5468  val_at=0.4772  val_isAt=0.6165
  epoch   3  loss=1.8009  val_global=0.6259  val_at=0.5781  val_isAt=0.6738
  epoch   4  loss=1.6936  val_global=0.6521  val_at=0.6145  val_isAt=0.6896
  epoch   5  loss=1.5854  val_global=0.6822  val_at=0.6691  val_isAt=0.6952
  epoch   6  loss=1.5156  val_global=0.6205  val_at=0.5422  val_isAt=0.6989
  epoch   7  loss=1.4561  val_

## 30 days windows

In [22]:
# 30 days
!python scripts/train_mask_contrastive.py \
    --npz /content/HIPE/runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2.npz \
    --feature-set concat_t \
    --contrastive-at ordinal --base-margin 1.0 \
    --experiment-id T1.4or5_mask_contrastive_ordinal_m1_at-test_30d


Loading cache /content/HIPE/runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2.npz
  X shape           : (1251, 2319)
  feature set       : concat_t
  template / model  : M2 / dbmdz/bert-base-historic-multilingual-cased
  train (matched)   : 1063
  test  (matched)   : 188
  val carved        : 107
  train (after val) : 956

Training: epochs=20 alpha=0.7 contrastive(at)=ordinal contrastive(isAt)=supcon k_per_class=16
  epoch   0  loss=2.5149  val_global=0.4584  val_at=0.3333  val_isAt=0.5835
  epoch   1  loss=2.2557  val_global=0.4946  val_at=0.3702  val_isAt=0.6190
  epoch   2  loss=2.0494  val_global=0.5298  val_at=0.3793  val_isAt=0.6803
  epoch   3  loss=1.8368  val_global=0.6037  val_at=0.5004  val_isAt=0.7071
  epoch   4  loss=1.6936  val_global=0.6007  val_at=0.5284  val_isAt=0.6729
  epoch   5  loss=1.5999  val_global=0.6244  val_at=0.5925  val_isAt=0.6563
  epoch   6  loss=1.5027  val_global=0.6280  val_at=0.5535  val_isAt=0.7026
  epoch   7  loss=1.4484  val_global=0.643

In [40]:
# CE-only baseline (no contrastive contribution)
!python scripts/train_mask_contrastive.py \
    --npz /content/HIPE/runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2_L-1_-4_-7.npz \
    --alpha 1.0 --contrastive-at none --contrastive-isAt none \
    --experiment-id T1.4or5_mask_contrastive_CEonly_at-test_30d

Loading cache /content/HIPE/runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2_L-1_-4_-7.npz
  X shape           : (1251, 2319)
  feature set       : concat_t
  template / model  : M2 / dbmdz/bert-base-historic-multilingual-cased
  train (matched)   : 1063
  test  (matched)   : 188
  val carved        : 107
  train (after val) : 956

Training: epochs=20 alpha=1.0 contrastive(at)=none contrastive(isAt)=none k_per_class=16
  epoch   0  loss=1.3931  val_global=0.4288  val_at=0.3333  val_isAt=0.5242
  epoch   1  loss=1.0355  val_global=0.4675  val_at=0.3530  val_isAt=0.5820
  epoch   2  loss=0.7429  val_global=0.5345  val_at=0.4388  val_isAt=0.6303
  epoch   3  loss=0.5055  val_global=0.6223  val_at=0.5679  val_isAt=0.6766
  epoch   4  loss=0.3541  val_global=0.6084  val_at=0.5541  val_isAt=0.6628
  epoch   5  loss=0.2514  val_global=0.6316  val_at=0.5837  val_isAt=0.6794
  epoch   6  loss=0.1822  val_global=0.6399  val_at=0.6106  val_isAt=0.6693
  epoch   7  loss=0.1190  val_global=

In [41]:
# SupCon on at (vs the ordinal default)
!python scripts/train_mask_contrastive.py \
    --npz /content/HIPE/runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2_L-1_-4_-7.npz \
    --contrastive-at supcon --contrastive-isAt supcon \
    --experiment-id T1.4or5_mask_contrastive_supcon_at-test_30d

Loading cache /content/HIPE/runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2_L-1_-4_-7.npz
  X shape           : (1251, 2319)
  feature set       : concat_t
  template / model  : M2 / dbmdz/bert-base-historic-multilingual-cased
  train (matched)   : 1063
  test  (matched)   : 188
  val carved        : 107
  train (after val) : 956

Training: epochs=20 alpha=0.7 contrastive(at)=supcon contrastive(isAt)=supcon k_per_class=16
  epoch   0  loss=3.3518  val_global=0.4205  val_at=0.3333  val_isAt=0.5076
  epoch   1  loss=3.0763  val_global=0.4722  val_at=0.3846  val_isAt=0.5597
  epoch   2  loss=2.8492  val_global=0.5091  val_at=0.4175  val_isAt=0.6006
  epoch   3  loss=2.6428  val_global=0.6120  val_at=0.5436  val_isAt=0.6803
  epoch   4  loss=2.4827  val_global=0.6118  val_at=0.5479  val_isAt=0.6758
  epoch   5  loss=2.3795  val_global=0.6464  val_at=0.5800  val_isAt=0.7128
  epoch   6  loss=2.2849  val_global=0.6313  val_at=0.5767  val_isAt=0.6859
  epoch   7  loss=2.2283  val_glo

In [39]:
# Aggressive ordinal margin
!python scripts/train_mask_contrastive.py \
    --npz "$CACHE" --feature-set "$FEATURE_SET" \
    --contrastive-at ordinal --base-margin 1.0 \
    --experiment-id T1.4or5_mask_contrastive_ordinal_m1_at-test_30d

Loading cache /content/HIPE/runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2_L-1_-4_-7.npz
  X shape           : (1251, 3855)
  feature set       : concat_l_t
  template / model  : M2 / dbmdz/bert-base-historic-multilingual-cased
  train (matched)   : 1063
  test  (matched)   : 188
  val carved        : 107
  train (after val) : 956

Training: epochs=20 alpha=0.7 contrastive(at)=ordinal contrastive(isAt)=supcon k_per_class=16
  epoch   0  loss=2.5168  val_global=0.4700  val_at=0.3333  val_isAt=0.6067
  epoch   1  loss=2.2331  val_global=0.5237  val_at=0.4090  val_isAt=0.6385
  epoch   2  loss=2.0043  val_global=0.5489  val_at=0.4684  val_isAt=0.6294
  epoch   3  loss=1.8022  val_global=0.6307  val_at=0.5580  val_isAt=0.7035
  epoch   4  loss=1.6914  val_global=0.6432  val_at=0.6032  val_isAt=0.6831
  epoch   5  loss=1.5831  val_global=0.6730  val_at=0.6470  val_isAt=0.6989
  epoch   6  loss=1.5108  val_global=0.6190  val_at=0.5390  val_isAt=0.6989
  epoch   7  loss=1.4565  val_

## Refresh the cross-config disagreement matrix + report

After every batch of new runs, re-aggregate so the comparison tables and disagreement matrix include the MASK cells:


In [42]:
!python scripts/aggregate_results.py
!python scripts/disagreement_analysis.py
!python scripts/generate_report.py

  T1.1_llm_zeroshot_PA+PB_split_v2: n=188  global=0.4962
  T1.1_llm_zeroshot_PAB_deepinfra_Meta-Llama-31-8B-Instruct_at-test: n=188  global=0.4489
  T1.1_llm_zeroshot_PA_deepinfra_Meta-Llama-31-8B-Instruct_at-test_reparsed: n=188  global=0.4315
  T1.1_llm_zeroshot_PA_deepinfra_Meta-Llama-31-8B-Instruct_at-test: n=188  global=0.4395
  T1.1_llm_zeroshot_PA_v2_fixed_prompt: n=188  global=0.4463
  T1.1_llm_zeroshot_PB_deepinfra_Meta-Llama-31-8B-Instruct_at-test_reparsed: n=188  global=0.4776
  T1.1_llm_zeroshot_PB_deepinfra_Meta-Llama-31-8B-Instruct_at-test: n=188  global=0.4196
  T1.1_llm_zeroshot_PB_v2_fixed_prompt: n=188  global=0.4666
  T1.1_llm_zeroshot_PR_deepinfra_Meta-Llama-31-8B-Instruct_at-test: n=188  global=0.5375
  T1.4or5_mask_C1_mask_LR_at_at-test: n=188  global=0.5229
  T1.4or5_mask_C1_mask_LR_isAt_at-test: n=188  global=0.4886
  T1.4or5_mask_C4_mask+e1+e2+temporal_LR_at_at-test+SDov_PROBABLE_from_FALSE_nw0.05: n=188  global=0.7911
  T1.4or5_mask_C4_mask+e1+e2+temporal_LR_a

ablate temporals features

In [43]:
!python scripts/train_mask_contrastive.py \
    --npz /content/HIPE/runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2.npz \
    --feature-set concat \
    --contrastive-at ordinal --contrastive-isAt none --alpha 1.0 \
    --base-margin 1.0 \
    --experiment-id T1.4or5_mask_contrastive_ordinal_m1_at-test_notemporal

Loading cache /content/HIPE/runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2.npz
  X shape           : (1251, 2304)
  feature set       : concat
  template / model  : M2 / dbmdz/bert-base-historic-multilingual-cased
  train (matched)   : 1063
  test  (matched)   : 188
  val carved        : 107
  train (after val) : 956

Training: epochs=20 alpha=1.0 contrastive(at)=ordinal contrastive(isAt)=none k_per_class=16
  epoch   0  loss=1.4081  val_global=0.4809  val_at=0.3421  val_isAt=0.6197
  epoch   1  loss=1.0455  val_global=0.5309  val_at=0.4140  val_isAt=0.6478
  epoch   2  loss=0.7348  val_global=0.5862  val_at=0.4495  val_isAt=0.7229
  epoch   3  loss=0.5017  val_global=0.6313  val_at=0.5592  val_isAt=0.7035
  epoch   4  loss=0.3426  val_global=0.6358  val_at=0.5987  val_isAt=0.6729
  epoch   5  loss=0.2516  val_global=0.6254  val_at=0.5981  val_isAt=0.6526
  epoch   6  loss=0.1769  val_global=0.6535  val_at=0.6470  val_isAt=0.6600
  epoch   7  loss=0.1225  val_global=0.6441  v

In [39]:
!python scripts/train_mask_contrastive.py \
    --npz runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2.npz \
    --feature-set concat_t \
    --contrastive-at ordinal --contrastive-isAt none --alpha 1.0 \
    --base-margin 1.0 \
    --drop-timex-flag \
    --experiment-id T1.4or5_mask_contrastive_ordinal_m1_at-test_drop_timex

Loading cache runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2.npz
  --drop-timex-flag : zeroed temporal[:,10] (101 ones -> 0)
  X shape           : (1251, 2319)
  feature set       : concat_t
  template / model  : M2 / dbmdz/bert-base-historic-multilingual-cased
  train (matched)   : 1063
  test  (matched)   : 188
  val carved        : 107
  train (after val) : 956

Training: epochs=20 alpha=1.0 contrastive(at)=ordinal contrastive(isAt)=none k_per_class=16
  epoch   0  loss=1.3887  val_global=0.4538  val_at=0.3333  val_isAt=0.5742
  epoch   1  loss=1.0393  val_global=0.5212  val_at=0.4039  val_isAt=0.6385
  epoch   2  loss=0.7399  val_global=0.5916  val_at=0.4834  val_isAt=0.6998
  epoch   3  loss=0.4930  val_global=0.6181  val_at=0.5623  val_isAt=0.6738
  epoch   4  loss=0.3411  val_global=0.6256  val_at=0.5755  val_isAt=0.6758
  epoch   5  loss=0.2514  val_global=0.6338  val_at=0.6012  val_isAt=0.6665
  epoch   6  loss=0.1776  val_global=0.6614  val_at=0.5905  val_isAt=0.732

In [41]:
!python scripts/combine_split_predictions.py \
    --pa /content/HIPE/logs/ablations/T1.4or5_mask_contrastive_ordinal_m1_at-test_drop_timex_predictions.jsonl \
    --pb /content/HIPE/logs/ablations/T1_hybrid_T15RFat_Llama70BrulesIsAt_predictions.jsonl \
    --experiment-id T1_hybrid_OrdinalDropTimexAt_Llama70BrulesIsAt

P-A rows: 188  P-B rows: 188  overlap: 188  union: 188
Wrote logs/ablations/T1_hybrid_OrdinalDropTimexAt_Llama70BrulesIsAt_predictions.jsonl

EVALUATION REPORT: T1_hybrid_OrdinalDropTimexAt_Llama70BrulesIsAt
n_instances:         188
Global score:        0.7022
MacroRecall(at):     0.5995
  recall TRUE       0.7727
  recall PROBABLE   0.3333
  recall FALSE      0.6923
MacroRecall(isAt):   0.8049
  recall TRUE       0.7632
  recall FALSE      0.8467
Confusion matrix (at)   rows=gold, cols=pred: ('TRUE', 'PROBABLE', 'FALSE')
              TRUE PROBABLE    FALSE
  TRUE          51        4       11
  PROBABLE       4        6        8
  FALSE         29        3       72
Confusion matrix (isAt) rows=gold, cols=pred: ('TRUE', 'FALSE')
              TRUE    FALSE
  TRUE          29        9
  FALSE         23      127
Wrote logs/ablations/T1_hybrid_OrdinalDropTimexAt_Llama70BrulesIsAt_report.json


In [44]:
import numpy as np
from pathlib import Path
for run in sorted(Path('runs/sd').iterdir()):
    sg = run / 'subgroups_PROBABLE.npz'
    if not sg.exists():
        continue
    z = np.load(sg, allow_pickle=True)
    n = len(z['feature_names'])
    s = run / 'summary.json'
    cfg = '?'
    if s.exists():
        import json
        cfg = json.loads(s.read_text()).get('config','?')
    print(f'{run.name:40s} config={cfg:8s} dim={n}')

SD-H_20260430_175226                     config=SD-H     dim=42
SD-H_full_at_20260430_231438             config=?        dim=42
SD-H_full_at_v2                          config=SD-H     dim=42


In [45]:
#!python scripts/discover_probable_subgroups.py --help  # check args
!python scripts/discover_probable_subgroups.py \
    --config SD-H --target PROBABLE \
    --out-dir runs/sd/SD-H_full_at_v3

usage: discover_probable_subgroups.py [-h] [--dataset DATASET] [--npz NPZ]
                                      [--split-csv SPLIT_CSV]
                                      [--config {SD-H,SD-HS,SD-HSP,SD-HQ,SD-HQS,SD-P}]
                                      [--qa-npz QA_NPZ]
                                      [--target TARGET [TARGET ...]]
                                      [--train-only | --no-train-only]
                                      [--hierarchy-cache HIERARCHY_CACHE]
                                      [--n-pca N_PCA]
                                      [--spectral-components SPECTRAL_COMPONENTS]
                                      [--spectral-neighbors SPECTRAL_NEIGHBORS]
                                      [--n-chains N_CHAINS]
                                      [--n-steps N_STEPS]
                                      [--temperature TEMPERATURE]
                                      [--annealing | --no-annealing]
                                     

In [46]:
# Inspect the rules first so you can judge overfitting risk
!cat runs/sd/SD-H_full_at_v2/rules_PROBABLE.txt

# Then layer overrides on top of the drop-flag predictions
!python scripts/apply_sd_overrides.py \
    --predictions logs/ablations/T1.4or5_mask_contrastive_ordinal_m1_at-test_drop_timex_predictions.jsonl \
    --sd-run runs/sd/SD-H_full_at_v2 \
    --target PROBABLE --only-from FALSE --min-nwracc 0.05

High-precision triggers for class PROBABLE discovered on the training pool.
Use them as soft hints — only when the surface evidence supports the inference.

1. When verb_is_present=1 AND verb_is_future=0 AND sentence_position_norm in [0.04,0.24] AND is_lead_paragraph=0 AND signal_negation=0 AND signal_present=0 AND has_timex_in_window=0 AND nearest_timex_distance_norm=0 AND person_is_deceased=0 AND person_status_known=0 AND ocr_quality in [0.998,1] AND entity_char_distance in [0.406,1] AND entities_adjacent=0 AND has_preposition_link=0 AND has_genitive_construction=0 AND has_hedging=0 AND n_hedging_words=0 AND has_subjunctive=0 AND person_mention_count in [0,0.9] AND location_mention_count=1 AND n_competing_locations in [0.3,0.4] AND verb_type_role=0 AND verb_type_birth_death=0 AND verb_type_communication=0 AND verb_indirect_evidence=0 AND direct_loc_count in [0,0.1] AND hierarchical_loc_count in [0,0.1] AND lang_en=0 → consider PROBABLE (precision 100% on training, NWRAcc=0.059, suppo

In [47]:
# 3) Override run-3 (hybrid). The script applies overrides to whatever
#    `at_predicted` the file contains, so feed the hybrid's predictions in.
!python scripts/apply_sd_overrides.py \
    --predictions logs/ablations/T1_hybrid_OrdinalDropTimexAt_Llama70BrulesIsAt_predictions.jsonl \
    --sd-run runs/sd/SD-H_full_at_v2 \
    --target PROBABLE --only-from FALSE --min-nwracc 0.05

Loading SD subgroups for target=PROBABLE  (config=SD-H)
  loaded 15 subgroups; 15 pass NWRAcc>=0.05 & precision>=0.0
Loading predictions: logs/ablations/T1_hybrid_OrdinalDropTimexAt_Llama70BrulesIsAt_predictions.jsonl
  rows: 188
Loading dataset: /content/HIPE/data/dataset_reference.jsonl
  aligned: 188/188 rows
  test feature matrix: (188, 47)
Feature dimensionality mismatch: SD has 42, test built 47. Check that SD config 'SD-H' is reproduced exactly on the test pool.


In [56]:
import json
s = json.load(open('runs/sd/SD-H_full_at_v2/summary.json'))
print(json.dumps(s, indent=2))

{
  "run_id": "SD-H_full_at_v2",
  "config": "SD-H",
  "dataset": "C:\\Users\\dnurb\\Documents\\MilitIA\\HIPE\\data\\dataset_reference.jsonl",
  "npz": null,
  "train_only": true,
  "n_features": 42,
  "n_rows": 1063,
  "feature_names": [
    "verb_is_present",
    "verb_is_past",
    "verb_is_negated",
    "verb_is_future",
    "sentence_position_norm",
    "is_lead_paragraph",
    "signal_negation",
    "signal_present",
    "signal_relative",
    "signal_none",
    "has_timex_in_window",
    "nearest_timex_distance_norm",
    "person_is_deceased",
    "person_status_known",
    "ocr_quality",
    "entity_char_distance",
    "entities_adjacent",
    "has_preposition_link",
    "has_genitive_construction",
    "has_role_title",
    "has_hedging",
    "n_hedging_words",
    "entity_in_quotes",
    "has_subjunctive",
    "person_mention_count",
    "location_mention_count",
    "cooccurrence_sentences",
    "n_competing_locations",
    "verb_type_movement",
    "verb_type_stative",
    

In [57]:
!python scripts/discover_probable_subgroups.py \
    --config SD-H \
    --target PROBABLE \
    --nwracc-threshold 0.05 \
    --top-k 30 \
    --cv \
    --run-id SD-H_full_at_v3

Loading dataset /content/HIPE/data/dataset_reference.jsonl
  rows: 1251
  restricting to baseline train split: 1063
  handcrafted block    : 47-d
Config SD-H: 47 total features (rows: 1063)
Feature matrix: (1063, 47)
Run directory: /content/HIPE/runs/sd/SD-H_full_at_v3

=== Target: PROBABLE  (positives = 102) ===
  discovered 14 subgroups in 141.5s (top NWRAcc = 0.078)
    [1] NWRAcc=0.078  prec=0.24  sup=12/50  |active|=47
        verb_is_present in [0,1] AND verb_is_past in [0,1] AND verb_is_negated=0 AND verb_is_future=0 AND sentence_position_norm in [0,0.88] AND is_lead_paragraph in [0,1] AND signal_negation=0 AND signal_present=0 AND signal_relative in [0,1] AND signal_none in [0,1] AND has_timex_in_window=0 AND nearest_timex_distance_norm=0 AND person_is_deceased=0 AND person_status_known in [0,1] AND ocr_quality in [0.947,0.994] AND entity_char_distance in [0.024,0.736] AND entities_adjacent in [0,1] AND has_preposition_link=0 AND has_genitive_construction=0 AND has_role_title i

In [58]:
!python scripts/apply_sd_overrides.py \
    --predictions /content/HIPE/logs/ablations/T1.4or5_mask_contrastive_ordinal_m1_at-test_drop_timex_predictions.jsonl \
    --sd-run /content/HIPE/runs/sd/SD-H_full_at_v3 \
    --target PROBABLE --only-from FALSE --min-nwracc 0.05

Loading SD subgroups for target=PROBABLE  (config=SD-H)
  loaded 14 subgroups; 14 pass NWRAcc>=0.05 & precision>=0.0
Loading predictions: /content/HIPE/logs/ablations/T1.4or5_mask_contrastive_ordinal_m1_at-test_drop_timex_predictions.jsonl
  rows: 188
Loading dataset: /content/HIPE/data/dataset_reference.jsonl
  aligned: 188/188 rows
  test feature matrix: (188, 47)
Applied 9 overrides (at)
Wrote /content/HIPE/logs/ablations/T1.4or5_mask_contrastive_ordinal_m1_at-test_drop_timex+SDov_PROBABLE_from_FALSE_nw0.05_predictions.jsonl

EVALUATION REPORT: T1.4or5_mask_contrastive_ordinal_m1_at-test_drop_timex+SDov_PROBABLE_from_FALSE_nw0.05
n_instances:         188
Global score:        0.7186
MacroRecall(at):     0.6390
  recall TRUE       0.7727
  recall PROBABLE   0.5000
  recall FALSE      0.6442
MacroRecall(isAt):   0.7982
  recall TRUE       0.7632
  recall FALSE      0.8333
Confusion matrix (at)   rows=gold, cols=pred: ('TRUE', 'PROBABLE', 'FALSE')
              TRUE PROBABLE    FALSE
  

In [59]:
!python scripts/apply_sd_overrides.py \
    --predictions logs/ablations/T1_hybrid_OrdinalDropTimexAt_Llama70BrulesIsAt_predictions.jsonl \
    --sd-run runs/sd/SD-H_full_at_v3 \
    --target PROBABLE --only-from FALSE --min-nwracc 0.05

Loading SD subgroups for target=PROBABLE  (config=SD-H)
  loaded 14 subgroups; 14 pass NWRAcc>=0.05 & precision>=0.0
Loading predictions: logs/ablations/T1_hybrid_OrdinalDropTimexAt_Llama70BrulesIsAt_predictions.jsonl
  rows: 188
Loading dataset: /content/HIPE/data/dataset_reference.jsonl
  aligned: 188/188 rows
  test feature matrix: (188, 47)
Applied 9 overrides (at)
Wrote /content/HIPE/logs/ablations/T1_hybrid_OrdinalDropTimexAt_Llama70BrulesIsAt+SDov_PROBABLE_from_FALSE_nw0.05_predictions.jsonl

EVALUATION REPORT: T1_hybrid_OrdinalDropTimexAt_Llama70BrulesIsAt+SDov_PROBABLE_from_FALSE_nw0.05
n_instances:         188
Global score:        0.7219
MacroRecall(at):     0.6390
  recall TRUE       0.7727
  recall PROBABLE   0.5000
  recall FALSE      0.6442
MacroRecall(isAt):   0.8049
  recall TRUE       0.7632
  recall FALSE      0.8467
Confusion matrix (at)   rows=gold, cols=pred: ('TRUE', 'PROBABLE', 'FALSE')
              TRUE PROBABLE    FALSE
  TRUE          51        5       10
  P

In [60]:
# 4) Refresh leaderboard
!python scripts/aggregate_results.py
!python scripts/generate_report.py

  T1.1_llm_zeroshot_PA+PB_split_v2: n=188  global=0.4962
  T1.1_llm_zeroshot_PAB_deepinfra_Meta-Llama-31-8B-Instruct_at-test: n=188  global=0.4489
  T1.1_llm_zeroshot_PA_deepinfra_Meta-Llama-31-8B-Instruct_at-test_reparsed: n=188  global=0.4315
  T1.1_llm_zeroshot_PA_deepinfra_Meta-Llama-31-8B-Instruct_at-test: n=188  global=0.4395
  T1.1_llm_zeroshot_PA_v2_fixed_prompt: n=188  global=0.4463
  T1.1_llm_zeroshot_PB_deepinfra_Meta-Llama-31-8B-Instruct_at-test_reparsed: n=188  global=0.4776
  T1.1_llm_zeroshot_PB_deepinfra_Meta-Llama-31-8B-Instruct_at-test: n=188  global=0.4196
  T1.1_llm_zeroshot_PB_v2_fixed_prompt: n=188  global=0.4666
  T1.1_llm_zeroshot_PR_deepinfra_Meta-Llama-31-8B-Instruct_at-test: n=188  global=0.5375
  T1.4or5_mask_C1_mask_LR_at_at-test: n=188  global=0.5229
  T1.4or5_mask_C1_mask_LR_isAt_at-test: n=188  global=0.4886
  T1.4or5_mask_C4_mask+e1+e2+temporal_LR_at_at-test+SDov_PROBABLE_from_FALSE_nw0.05: n=188  global=0.7911
  T1.4or5_mask_C4_mask+e1+e2+temporal_LR_a

In [24]:
#import numpy as np, os, datetime
#p = 'runs/mask_dbmdz_bert_base_historic_multilingual_cased_M2_L-1_-4_-7.npz'
#print('mtime:', datetime.datetime.fromtimestamp(os.path.getmtime(p)))
#z = np.load(p)
#print('has_timex_in_window column count of 1.0s:', int(z['temporal'][:,10].sum()))


mtime: 2026-04-30 22:39:50
has_timex_in_window column count of 1.0s: 73


In [68]:
import json
from pathlib import Path
p = Path('runs/sd/SD-H_full_at_v3/cv_stability_PROBABLE.json')
print('size:', p.stat().st_size, 'bytes')
data = json.loads(p.read_text())
print('type:', type(data).__name__)
print('top-level keys:' , list(data.keys()) if isinstance(data, dict) else f'list len={len(data)}')
print(json.dumps(data, indent=2)[:1000])

size: 8893 bytes
type: dict
top-level keys: ['target', 'n_folds', 'min_precision', 'min_folds', 'semantic_threshold', 'elapsed_seconds', 'stable_patterns', 'n_stable', 'semantic_stable_patterns', 'n_semantic_stable']
{
  "target": "PROBABLE",
  "n_folds": 5,
  "min_precision": 0.3,
  "min_folds": 3,
  "semantic_threshold": 0.5,
  "elapsed_seconds": 163.66,
  "stable_patterns": [],
  "n_stable": 0,
  "semantic_stable_patterns": [
    {
      "representative_pattern": "verb_is_present in [0,1] AND verb_is_past in [0,1] AND verb_is_negated in [0,1] AND verb_is_future=0 AND sentence_position_norm in [0.06,0.18] AND is_lead_paragraph=0 AND signal_negation=0 AND signal_present=0 AND signal_relative=0 AND signal_none=1 AND has_timex_in_window=0 AND nearest_timex_distance_norm=0 AND person_is_deceased=0 AND person_status_known=0 AND ocr_quality in [0.974,1] AND entity_char_distance in [0.496,1] AND entities_adjacent=0 AND has_preposition_link=0 AND has_genitive_construction=0 AND has_role_titl

In [69]:
import json
r = json.load(open('runs/sd/SD-H_full_at_v3/cv_stability_PROBABLE.json'))
print(f'string-stable     : {r["n_stable"]}')
print(f'semantic-stable   : {r["n_semantic_stable"]}')
print()
for i, p in enumerate(r['semantic_stable_patterns']):
    # Each entry usually has: representative_pattern, n_folds_present,
    # avg_precision, avg_support, jaccard_to_representative, ...
    print(f'--- semantic stable #{i+1} ---')
    for k in ('n_folds_present', 'mean_precision', 'mean_support', 'mean_nwracc',
              'mean_extent_jaccard', 'mean_jaccard'):
        if k in p:
            print(f'  {k:25s} : {p[k]}')
    rep = p.get('representative_pattern', '')
    print(f'  representative (head): {rep[:200]}…')
    print()

string-stable     : 0
semantic-stable   : 2

--- semantic stable #1 ---
  representative (head): verb_is_present in [0,1] AND verb_is_past in [0,1] AND verb_is_negated in [0,1] AND verb_is_future=0 AND sentence_position_norm in [0.06,0.18] AND is_lead_paragraph=0 AND signal_negation=0 AND signal_…

--- semantic stable #2 ---
  representative (head): verb_is_present in [0,1] AND verb_is_past in [0,1] AND verb_is_negated=0 AND verb_is_future=0 AND sentence_position_norm in [0,0.88] AND is_lead_paragraph in [0,1] AND signal_negation=0 AND signal_pre…



In [70]:
import json
r = json.load(open('runs/sd/SD-H_full_at_v3/cv_stability_PROBABLE.json'))
p = r['semantic_stable_patterns'][0]
print('keys on each pattern:', sorted(p.keys()))
print()
print(json.dumps(p, indent=2)[:2500])

keys on each pattern: ['folds_stable', 'mean_train_nwracc', 'mean_val_precision', 'mean_val_recall', 'member_patterns', 'n_folds_seen', 'n_folds_stable', 'n_members', 'representative_pattern']

{
  "representative_pattern": "verb_is_present in [0,1] AND verb_is_past in [0,1] AND verb_is_negated in [0,1] AND verb_is_future=0 AND sentence_position_norm in [0.06,0.18] AND is_lead_paragraph=0 AND signal_negation=0 AND signal_present=0 AND signal_relative=0 AND signal_none=1 AND has_timex_in_window=0 AND nearest_timex_distance_norm=0 AND person_is_deceased=0 AND person_status_known=0 AND ocr_quality in [0.974,1] AND entity_char_distance in [0.496,1] AND entities_adjacent=0 AND has_preposition_link=0 AND has_genitive_construction=0 AND has_role_title=0 AND has_hedging=0 AND n_hedging_words=0 AND entity_in_quotes in [0,1] AND has_subjunctive=0 AND person_mention_count in [0.1,1] AND location_mention_count in [0,1] AND cooccurrence_sentences in [0,0.2] AND n_competing_locations in [0.1,0.3] AN

In [71]:
!python scripts/apply_sd_overrides.py \
    --predictions logs/ablations/T1.4or5_mask_contrastive_ordinal_m1_at-test_drop_timex_predictions.jsonl \
    --sd-run runs/sd/SD-H_full_at_v2 \
    --target PROBABLE --only-from FALSE --min-nwracc 0.05

Loading SD subgroups for target=PROBABLE  (config=SD-H)
  loaded 15 subgroups; 15 pass NWRAcc>=0.05 & precision>=0.0
Loading predictions: logs/ablations/T1.4or5_mask_contrastive_ordinal_m1_at-test_drop_timex_predictions.jsonl
  rows: 188
Loading dataset: /content/HIPE/data/dataset_reference.jsonl
  aligned: 188/188 rows
  test feature matrix: (188, 47)
  sliced test matrix to SD's 42 columns (builder produced 47; dropped 5 extras)
Applied 8 overrides (at)
Wrote /content/HIPE/logs/ablations/T1.4or5_mask_contrastive_ordinal_m1_at-test_drop_timex+SDov_PROBABLE_from_FALSE_nw0.05_predictions.jsonl

EVALUATION REPORT: T1.4or5_mask_contrastive_ordinal_m1_at-test_drop_timex+SDov_PROBABLE_from_FALSE_nw0.05
n_instances:         188
Global score:        0.6985
MacroRecall(at):     0.5987
  recall TRUE       0.7727
  recall PROBABLE   0.3889
  recall FALSE      0.6346
MacroRecall(isAt):   0.7982
  recall TRUE       0.7632
  recall FALSE      0.8333
Confusion matrix (at)   rows=gold, cols=pred: ('T

In [72]:
!python scripts/discover_probable_subgroups.py \
    --config SD-H \
    --target TRUE FALSE \
    --cv \
    --run-id SD-H_full_at_v3

Loading dataset /content/HIPE/data/dataset_reference.jsonl
  rows: 1251
  restricting to baseline train split: 1063
  handcrafted block    : 47-d
Config SD-H: 47 total features (rows: 1063)
Feature matrix: (1063, 47)
Run directory: /content/HIPE/runs/sd/SD-H_full_at_v3

=== Target: TRUE  (positives = 375) ===
  no subgroups crossed threshold (elapsed 144.6s)
  wrote /content/HIPE/runs/sd/SD-H_full_at_v3/subgroups_TRUE.json
  running 5-fold stability ...
[fold 0] discovered 0 subgroups; mean held-out precision = 0.000
[fold 1] discovered 0 subgroups; mean held-out precision = 0.000
[fold 2] discovered 0 subgroups; mean held-out precision = 0.000
[fold 3] discovered 0 subgroups; mean held-out precision = 0.000
[fold 4] discovered 0 subgroups; mean held-out precision = 0.000
  string-stable patterns   : 0 (prec >= 0.3 on >= 3/5 folds)
  semantic-stable clusters : 0 (Jaccard >= 0.5, prec >= 0.3 on >= 3/5 folds)
  string-stable: 0  | semantic-stable: 0  (prec >= 0.3 on >= 3/5; Jaccard >= 0.

In [73]:
!python scripts/apply_sd_overrides.py \
    --predictions logs/ablations/T1.4or5_mask_contrastive_ordinal_m1_at-test_drop_timex_predictions.jsonl \
    --sd-run runs/sd/SD-H_full_at_v2 \
    --target PROBABLE --only-from FALSE \
    --min-nwracc 0.10 --min-precision 0.5 \
    --experiment-id T1.4or5_mask_contrastive_ordinal_m1_at-test_drop_timex+SDov_PROBABLE_strict

Loading SD subgroups for target=PROBABLE  (config=SD-H)
  loaded 15 subgroups; 0 pass NWRAcc>=0.1 & precision>=0.5
  no subgroups eligible — exiting without changes


In [74]:
!python scripts/apply_sd_overrides.py \
    --predictions logs/ablations/T1.4or5_mask_contrastive_ordinal_m1_at-test_drop_timex_predictions.jsonl \
    --sd-run runs/sd/SD-H_full_at_v2 \
    --target PROBABLE --only-from FALSE \
    --min-nwracc 0.05 --min-precision 0.7 \
    --experiment-id T1.4or5_mask_contrastive_ordinal_m1_at-test_drop_timex+SDov_PROBABLE_p07

Loading SD subgroups for target=PROBABLE  (config=SD-H)
  loaded 15 subgroups; 10 pass NWRAcc>=0.05 & precision>=0.7
Loading predictions: logs/ablations/T1.4or5_mask_contrastive_ordinal_m1_at-test_drop_timex_predictions.jsonl
  rows: 188
Loading dataset: /content/HIPE/data/dataset_reference.jsonl
  aligned: 188/188 rows
  test feature matrix: (188, 47)
  sliced test matrix to SD's 42 columns (builder produced 47; dropped 5 extras)
Applied 2 overrides (at)
Wrote /content/HIPE/logs/ablations/T1.4or5_mask_contrastive_ordinal_m1_at-test_drop_timex+SDov_PROBABLE_p07_predictions.jsonl

EVALUATION REPORT: T1.4or5_mask_contrastive_ordinal_m1_at-test_drop_timex+SDov_PROBABLE_p07
n_instances:         188
Global score:        0.7065
MacroRecall(at):     0.6148
  recall TRUE       0.7727
  recall PROBABLE   0.3889
  recall FALSE      0.6827
MacroRecall(isAt):   0.7982
  recall TRUE       0.7632
  recall FALSE      0.8333
Confusion matrix (at)   rows=gold, cols=pred: ('TRUE', 'PROBABLE', 'FALSE')
 

In [75]:
# run-3: hybrid with same drop-flag at-source — expected lift identical
!python scripts/apply_sd_overrides.py \
    --predictions logs/ablations/T1_hybrid_OrdinalDropTimexAt_Llama70BrulesIsAt_predictions.jsonl \
    --sd-run runs/sd/SD-H_full_at_v2 \
    --target PROBABLE --only-from FALSE \
    --min-nwracc 0.05 --min-precision 0.7 \
    --experiment-id T1_hybrid_OrdinalDropTimexAt_Llama70BrulesIsAt+SDov_PROBABLE_p07


Loading SD subgroups for target=PROBABLE  (config=SD-H)
  loaded 15 subgroups; 10 pass NWRAcc>=0.05 & precision>=0.7
Loading predictions: logs/ablations/T1_hybrid_OrdinalDropTimexAt_Llama70BrulesIsAt_predictions.jsonl
  rows: 188
Loading dataset: /content/HIPE/data/dataset_reference.jsonl
  aligned: 188/188 rows
  test feature matrix: (188, 47)
  sliced test matrix to SD's 42 columns (builder produced 47; dropped 5 extras)
Applied 2 overrides (at)
Wrote /content/HIPE/logs/ablations/T1_hybrid_OrdinalDropTimexAt_Llama70BrulesIsAt+SDov_PROBABLE_p07_predictions.jsonl

EVALUATION REPORT: T1_hybrid_OrdinalDropTimexAt_Llama70BrulesIsAt+SDov_PROBABLE_p07
n_instances:         188
Global score:        0.7098
MacroRecall(at):     0.6148
  recall TRUE       0.7727
  recall PROBABLE   0.3889
  recall FALSE      0.6827
MacroRecall(isAt):   0.8049
  recall TRUE       0.7632
  recall FALSE      0.8467
Confusion matrix (at)   rows=gold, cols=pred: ('TRUE', 'PROBABLE', 'FALSE')
              TRUE PROBAB

In [76]:

# run-2: RF + Llama70B isAt — different base classifier, so the override
# pattern hits a different set of FALSE predictions
!python scripts/apply_sd_overrides.py \
    --predictions logs/ablations/T1_hybrid_T15RFat_Llama70BrulesIsAt_predictions.jsonl \
    --sd-run runs/sd/SD-H_full_at_v2 \
    --target PROBABLE --only-from FALSE \
    --min-nwracc 0.05 --min-precision 0.7 \
    --experiment-id T1_hybrid_T15RFat_Llama70BrulesIsAt+SDov_PROBABLE_p07

Loading SD subgroups for target=PROBABLE  (config=SD-H)
  loaded 15 subgroups; 10 pass NWRAcc>=0.05 & precision>=0.7
Loading predictions: logs/ablations/T1_hybrid_T15RFat_Llama70BrulesIsAt_predictions.jsonl
  rows: 188
Loading dataset: /content/HIPE/data/dataset_reference.jsonl
  aligned: 188/188 rows
  test feature matrix: (188, 47)
  sliced test matrix to SD's 42 columns (builder produced 47; dropped 5 extras)
Applied 1 overrides (at)
Wrote /content/HIPE/logs/ablations/T1_hybrid_T15RFat_Llama70BrulesIsAt+SDov_PROBABLE_p07_predictions.jsonl

EVALUATION REPORT: T1_hybrid_T15RFat_Llama70BrulesIsAt+SDov_PROBABLE_p07
n_instances:         188
Global score:        0.7322
MacroRecall(at):     0.6595
  recall TRUE       0.6515
  recall PROBABLE   0.5000
  recall FALSE      0.8269
MacroRecall(isAt):   0.8049
  recall TRUE       0.7632
  recall FALSE      0.8467
Confusion matrix (at)   rows=gold, cols=pred: ('TRUE', 'PROBABLE', 'FALSE')
              TRUE PROBABLE    FALSE
  TRUE          43   

Inspect the headline numbers:

In [38]:
import json
from pathlib import Path

PROJECT = Path('/content/HIPE')
results = json.loads((PROJECT / 'logs' / 'final' / 'results.json').read_text())
print(f"Total experiments scored: {results['n_experiments']}")
print('\nTop-12 by GlobalScore:')
for r in results['ranking_by_global_score'][:12]:
    eid = r['experiment_id']
    gs = r['global_score']
    print(f"  {eid:75s} {gs:.4f}")

Total experiments scored: 224

Top-12 by GlobalScore:
  T1.4or5_mask_C4_mask+e1+e2+temporal_LR_at_at-test+SDov_PROBABLE_from_FALSE_nw0.05 0.7911
  T1_hybrid_T15RFat_Llama70BrulesIsAt                                         0.7338
  T1.4or5_mask_contrastive_ordinal_m1_at-test                                 0.7189
  T1_hybrid_RFat_MASKC4isAt_at-test                                           0.7142
  T1_hybrid_T15RFat_Llama70BisAt_v2                                           0.7120
  T1.4or5_mask_contrastive_CEonly_at-test                                     0.6969
  T1_hybrid_T15RFat_Llama70BisAt                                              0.6786
  T1.6_rf_sd_dbmdz_bert_base_historic_multilingual_cased_M2_mlp_base          0.6740
  T1.6_rf_sd_dbmdz_bert_base_historic_multilingual_cased_M2_lr_base           0.6679
  T1.6_rf_sd_dbmdz_bert_base_historic_multilingual_cased_M2_lr_evidence       0.6673
  T2_ksweep_k8_nodiv_PR_deepinfra_Meta-Llama-31-8B-Instruct_at-test           0.6664
  T1.

In [39]:
# open evaluation report
from pathlib import Path

PROJECT = Path('/content/HIPE')
print((PROJECT / 'logs' / 'final' / 'evaluation_report.md').read_text()[:4000])  # head only

# HIPE-2026 Person-Place Relation Extraction — Evaluation Report
_Generated 2026-05-01T07:39:54.694199 from `logs/final/results.json` (224 experiments)_
## Executive summary
- **Best overall:** `T1.4or5_mask_C4_mask+e1+e2+temporal_LR_at_at-test+SDov_PROBABLE_from_FALSE_nw0.05`  global = **0.7911**, MR(at) = 0.5821, MR(isAt) = 1.0000
- **Best overall configuration:** **per-task hybrid** — Handcrafted RF for `at` (MR=0.6627) plus MASK C4 LR (mask + e1 + e2 + temporal) for `isAt` (MR=0.7658). **Global = 0.7142** — exceeds every single-classifier configuration tested.
- **Best single-classifier (both tasks):** Handcrafted RF (mean=0.688).
- **Best LLM (Llama 3.1 8B, P-R zero-shot):** global ≈ 0.538.
- **Score gap LLM-vs-hybrid:** ~0.18 — the smaller open LLM trails the simple-feature hybrid by a wide margin.
- **Adding context (RAG / Wikidata / temporal) hurts the small LLM modestly** after fixing token-budget truncation — the model gets distracted; expect a stronger model to behave differ

## Bundle artefacts for download

Compress and download what you need. With Drive mounted, the caches are already persisted; this just packages the things small enough to ship over a browser.

In [40]:
!tar czf /content/hipe_mask_artefacts.tar.gz \
    logs/ablations \
    logs/final \
    runs/mask_grid_eval \
    runs/phase0_mask_diag

!ls -la /content/hipe_mask_artefacts.tar.gz

tar: logs/ablations/smoke_PAB_2_predictions.jsonl: file changed as we read it
tar: logs/ablations/smoke_PAB_2_report.json: file changed as we read it
tar: logs/ablations/T1.1_llm_zeroshot_PA_deepinfra_Meta-Llama-31-8B-Instruct_at-test_report.json: file changed as we read it
tar: logs/ablations/T1.1_llm_zeroshot_PA_deepinfra_Meta-Llama-31-8B-Instruct_at-test_predictions.jsonl: file changed as we read it
tar: logs/ablations/T1.1_llm_zeroshot_PB_deepinfra_Meta-Llama-31-8B-Instruct_at-test_predictions.jsonl: file changed as we read it
tar: logs/ablations/T1.1_llm_zeroshot_PB_deepinfra_Meta-Llama-31-8B-Instruct_at-test_report.json: file changed as we read it
tar: logs/ablations/T1.1_llm_zeroshot_PAB_deepinfra_Meta-Llama-31-8B-Instruct_at-test_report.json: file changed as we read it
tar: logs/ablations/compare_PA-B-AB-R_deepinfra_at-test.json: file changed as we read it
tar: logs/ablations/T1.1_llm_zeroshot_PR_deepinfra_Meta-Llama-31-8B-Instruct_at-test_predictions.jsonl: file changed as we 

In [41]:
from google.colab import files
files.download('/content/hipe_mask_artefacts.tar.gz')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>